begin;
select plan(12);
select has_table('public','project_templates','project templates exist');
select has_table('public','creator_projects','creator projects exist');
select has_table('public','project_assets','project assets exist');
select has_table('public','creator_portfolios','portfolios exist');
select has_table('public','portfolio_items','portfolio items exist');
select has_table('public','creation_resources','resources exist');
select has_table('public','live_classes','classes exist');
select has_table('public','class_registrations','class registrations exist');
select has_table('public','creator_website_requests','website workflow exists');
select has_table('public','creation_activity','activity exists');
select ok((select not public from storage.buckets where id='creation-station-private'),'storage bucket is private');
select ok((select count(*)>=3 from public.project_templates),'tier templates seeded');
select * from finish();
rollback;
