"use client";
import { useEffect, useMemo, useState } from "react";
type Activity={id:string;title:string;track:string;ages:string;time:string;level:string;description:string;learn:string[];challenge:string};
const activities:Activity[]=[
{id:"speak-up",title:"Speak Up Without Blowing Up",track:"People Skills",ages:"12+",time:"35 min",level:"Start here",description:"Practice saying what needs to be said with clarity, backbone, and respect.",learn:["Name the real issue","Separate facts from assumptions","Make a clear request"],challenge:"Rewrite one heated response as a calm, direct statement."},
{id:"money-map",title:"Build a Real-World Money Map",track:"Money & Work",ages:"14+",time:"45 min",level:"Core skill",description:"See where money comes from, where it goes, and what your choices actually cost.",learn:["Read income and expenses","Separate wants from needs","Plan for a real goal"],challenge:"Map one month of expected income, bills, savings, and spending."},
{id:"water-ready",title:"How Much Water Do You Really Need?",track:"Sustainability",ages:"All ages",time:"30 min",level:"Hands-on",description:"Calculate household water needs and build a practical backup plan using what you have.",learn:["Estimate daily use","Prioritize drinking and sanitation","Compare storage options"],challenge:"Calculate a three-day water plan for your household."},
{id:"hard-times",title:"Stay Useful in Hard Times",track:"Strength & Readiness",ages:"12+",time:"40 min",level:"Core skill",description:"Replace panic with a simple process for thinking, choosing, and moving forward.",learn:["Assess what is true","Identify what you control","Choose the next useful action"],challenge:"Run the process against one real problem you are facing."},
{id:"food-system",title:"See Food as a System",track:"Food & Land",ages:"All ages",time:"50 min",level:"Field lesson",description:"Follow the connections between soil, water, animals, people, waste, and nourishment.",learn:["Trace inputs and outputs","Spot waste that can become value","Design a simple local loop"],challenge:"Draw the food system around one meal on your table."},
{id:"team-code",title:"Write Your Family Team Code",track:"Family & Community",ages:"All ages",time:"45 min",level:"Do together",description:"Turn shared values into practical agreements about how your family works together.",learn:["Choose real values","Define responsibility","Create repair rules"],challenge:"Agree on five rules your whole team can explain and use."}
];
const tracks=[
{name:"People Skills",mark:"01",copy:"Communication, emotional intelligence, confidence, and handling difficult people."},
{name:"Money & Work",mark:"02",copy:"Money sense, responsibility, practical work, and building something of your own."},
{name:"Strength & Readiness",mark:"03",copy:"Critical thinking, courage, preparedness, and staying useful under pressure."},
{name:"Family & Community",mark:"04",copy:"Teamwork, accountability, leadership, service, and finding your people."},
{name:"Sustainability",mark:"05",copy:"Water, resourcefulness, low-input living, and working with what you’ve got."},
{name:"Food & Land",mark:"06",copy:"Real food systems, soil, animals, growing, and natural independence."}
];
export default function Home(){
const[filter,setFilter]=useState("All"),[selected,setSelected]=useState<Activity|null>(null),[plan,setPlan]=useState<string[]>([]),[done,setDone]=useState<string[]>([]);
useEffect(()=>{try{setPlan(JSON.parse(localStorage.getItem("rra-plan")||"[]"));setDone(JSON.parse(localStorage.getItem("rra-done")||"[]"))}catch{}},[]);
const save=(key:string,value:string[])=>{key==="rra-plan"?setPlan(value):setDone(value);try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const visible=useMemo(()=>filter==="All"?activities:activities.filter(a=>a.track===filter),[filter]);
const planned=plan.map(id=>activities.find(a=>a.id===id)).filter(Boolean) as Activity[];
const togglePlan=(id:string)=>save("rra-plan",plan.includes(id)?plan.filter(x=>x!==id):[...plan,id]);
const toggleDone=(id:string)=>save("rra-done",done.includes(id)?done.filter(x=>x!==id):[...done,id]);
return <main>
<header className="topbar"><a className="brand" href="#top" aria-label="Rebel Ranch Academy home"><span>Rebel Ranch</span><strong>Academy</strong></a><nav aria-label="Primary navigation"><a href="#tracks">Explore tracks</a><a href="#activities">Try a lesson</a><a href="#plan">My plan <b>{plan.length}</b></a></nav></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">REAL PEOPLE. REAL SKILLS. REAL COMMUNITY.</p><h1>Life doesn’t come with a lesson plan. <em>We built one anyway.</em></h1><p className="lede">Rebel Ranch Academy helps people build the skills to think clearly, work together, solve real problems, and depend less on broken systems.</p><div className="actions"><a className="button primary" href="#activities">Find your first lesson <span>→</span></a><a className="button secondary" href="#tracks">See what we teach</a></div></div><div className="hero-board"><div className="tape"/><p>THE REAL-LIFE CURRICULUM</p><ul><li><span>01</span>Know what you know.</li><li><span>02</span>Learn what you don’t.</li><li><span>03</span>Put it to work.</li><li><span>04</span>Teach somebody else.</li></ul><strong className="stamp">OWN YOUR LIFE</strong></div></section>
<section className="manifesto"><p>Not grades for memorizing.</p><strong>Skills for living.</strong><p>Online learning. Real-world action. No classroom required.</p></section>
<section className="section" id="tracks"><Heading kicker="CHOOSE YOUR GROUND" title="Six tracks. One capable human." copy="Start where life is pushing back. Every track builds knowledge you can use, share, and keep."/><div className="track-grid">{tracks.map(t=><button className="track-card" key={t.name} onClick={()=>{setFilter(t.name);document.getElementById("activities")?.scrollIntoView({behavior:"smooth"})}}><span>{t.mark}</span><h3>{t.name}</h3><p>{t.copy}</p><b>Explore this track →</b></button>)}</div></section>
<section className="section activities" id="activities"><Heading kicker="TRY THE ACADEMY" title="Pick something real." copy="No busywork. Every activity ends with something to do, decide, build, or change."/><div className="filters" aria-label="Filter activities">{["All",...tracks.map(t=>t.name)].map(n=><button key={n} className={filter===n?"active":""} onClick={()=>setFilter(n)}>{n}</button>)}</div><div className="activity-grid">{visible.map(a=><article className={`activity-card ${done.includes(a.id)?"complete":""}`} key={a.id}><div className="meta"><span>{a.track}</span><span>{a.ages} · {a.time}</span></div><h3>{a.title}</h3><p>{a.description}</p><div className="card-actions"><button onClick={()=>setSelected(a)}>Open lesson →</button><button className={plan.includes(a.id)?"saved":""} onClick={()=>togglePlan(a.id)}>{plan.includes(a.id)?"Remove from plan":"+ Add to my plan"}</button></div></article>)}</div></section>
<section className="plan-section" id="plan"><div className="plan-intro"><p className="eyebrow">YOUR NEXT MOVE</p><h2>Build your own path.</h2><p>Save activities here. Mark them complete when the work is done. Your plan stays on this device.</p></div><div className="plan-board"><div className="progress"><span style={{width:`${planned.length?(planned.filter(a=>done.includes(a.id)).length/planned.length)*100:0}%`}}/></div><p>{planned.filter(a=>done.includes(a.id)).length} of {planned.length} complete</p>{planned.length===0?<div className="empty"><strong>Your plan is wide open.</strong><p>Add a lesson that solves a problem you actually have.</p><a href="#activities">Browse activities →</a></div>:<ul className="plan-list">{planned.map(a=><li key={a.id}><button className={`check ${done.includes(a.id)?"checked":""}`} onClick={()=>toggleDone(a.id)} aria-label={`Mark ${a.title} ${done.includes(a.id)?"incomplete":"complete"}`}>{done.includes(a.id)?"✓":""}</button><button className="plan-title" onClick={()=>setSelected(a)}>{a.title}<small>{a.track} · {a.time}</small></button><button className="remove" onClick={()=>togglePlan(a.id)} aria-label={`Remove ${a.title}`}>×</button></li>)}</ul>}</div></section>
<section className="closing"><p className="eyebrow">RESPONSIBLE REBELS WANTED</p><h2>You do not have to know everything.<br/>You do need to keep learning.</h2><a className="button primary" href="#activities">Start where you are <span>→</span></a></section>
<footer><a className="brand" href="#top"><span>Rebel Ranch</span><strong>Academy</strong></a><p>Real-life skills. Sustainability. Independence.</p><p>Faith · Family · Freedom</p></footer>
{selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="lesson-modal" role="dialog" aria-modal="true" aria-labelledby="lesson-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close lesson">×</button><p className="eyebrow">{selected.track} · {selected.level}</p><h2 id="lesson-title">{selected.title}</h2><p className="lesson-desc">{selected.description}</p><h3>What you’ll learn</h3><ol>{selected.learn.map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ol><div className="challenge"><strong>Put it to work</strong><p>{selected.challenge}</p></div><div className="actions"><button className="button primary" onClick={()=>togglePlan(selected.id)}>{plan.includes(selected.id)?"Remove from my plan":"Add to my plan →"}</button><button className="button secondary" onClick={()=>toggleDone(selected.id)}>{done.includes(selected.id)?"✓ Completed":"Mark complete"}</button></div></section></div>}
</main>}
function Heading({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><p>{copy}</p></div>}
