-- AI-Agent: ChatGPT/GPT-5.6 Sol
-- Session: Rebel Ranch Marketplace — Social Content Hub
-- Purpose: Administrator-only source of truth for Rebel Ranch Ministries social content,
-- assets, reel assembly, and posting history. Repository migration only; production
-- application requires a separate owner approval.

create table if not exists public.social_content_items (
  id text primary key,
  program text not null,
  campaign text not null,
  campaign_day integer check (campaign_day is null or campaign_day > 0),
  title text not null,
  audience text not null default 'Everyone',
  goal text,
  purpose text,
  primary_message text,
  caption text,
  cta text,
  format text not null default 'Reel + Standalone'
    check (format in ('Reel','Standalone','Reel + Standalone')),
  status text not null default 'Planned'
    check (status in ('Planned','Visual Ready','Needs Review','Approved','Posted')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_content_assets (
  id bigint generated by default as identity primary key,
  content_item_id text not null references public.social_content_items(id) on delete cascade,
  asset_kind text not null default 'image'
    check (asset_kind in ('image','screenshot','video','document','other')),
  asset_status text not null default 'Planned'
    check (asset_status in ('Planned','Visual Ready','Needs Review','Approved','Archived')),
  master_filename text,
  preview_path text,
  external_archive_path text,
  alt_text text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_reels (
  id bigint generated by default as identity primary key,
  program text not null,
  campaign text,
  title text not null,
  objective text,
  caption text,
  cta text,
  status text not null default 'Draft'
    check (status in ('Draft','Ready for Review','Approved','Posted')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_reel_frames (
  reel_id bigint not null references public.social_reels(id) on delete cascade,
  content_item_id text not null references public.social_content_items(id) on delete cascade,
  frame_order integer not null check (frame_order > 0),
  frame_note text,
  created_at timestamptz not null default now(),
  primary key (reel_id, content_item_id),
  unique (reel_id, frame_order)
);

create table if not exists public.social_post_history (
  id bigint generated by default as identity primary key,
  content_item_id text references public.social_content_items(id) on delete set null,
  reel_id bigint references public.social_reels(id) on delete set null,
  platform text not null,
  published_at timestamptz not null default now(),
  post_url text,
  notes text,
  created_at timestamptz not null default now(),
  check (content_item_id is not null or reel_id is not null)
);

create index if not exists social_content_items_program_campaign_idx
  on public.social_content_items(program,campaign,campaign_day);
create index if not exists social_content_items_status_idx
  on public.social_content_items(status);
create index if not exists social_content_assets_item_idx
  on public.social_content_assets(content_item_id);
create index if not exists social_reels_program_campaign_idx
  on public.social_reels(program,campaign);
create index if not exists social_reel_frames_order_idx
  on public.social_reel_frames(reel_id,frame_order);
create index if not exists social_post_history_published_idx
  on public.social_post_history(published_at desc);

create trigger social_content_items_set_updated_at
before update on public.social_content_items
for each row execute function private.set_updated_at();

create trigger social_content_assets_set_updated_at
before update on public.social_content_assets
for each row execute function private.set_updated_at();

create trigger social_reels_set_updated_at
before update on public.social_reels
for each row execute function private.set_updated_at();

alter table public.social_content_items enable row level security;
alter table public.social_content_assets enable row level security;
alter table public.social_reels enable row level security;
alter table public.social_reel_frames enable row level security;
alter table public.social_post_history enable row level security;

revoke all on table public.social_content_items from anon;
revoke all on table public.social_content_assets from anon;
revoke all on table public.social_reels from anon;
revoke all on table public.social_reel_frames from anon;
revoke all on table public.social_post_history from anon;

revoke all on table public.social_content_items from authenticated;
revoke all on table public.social_content_assets from authenticated;
revoke all on table public.social_reels from authenticated;
revoke all on table public.social_reel_frames from authenticated;
revoke all on table public.social_post_history from authenticated;

grant select,insert,update,delete on table public.social_content_items to authenticated;
grant select,insert,update,delete on table public.social_content_assets to authenticated;
grant select,insert,update,delete on table public.social_reels to authenticated;
grant select,insert,update,delete on table public.social_reel_frames to authenticated;
grant select,insert,update,delete on table public.social_post_history to authenticated;
grant usage,select on sequence public.social_content_assets_id_seq to authenticated;
grant usage,select on sequence public.social_reels_id_seq to authenticated;
grant usage,select on sequence public.social_post_history_id_seq to authenticated;

create policy social_content_items_admin_all
on public.social_content_items for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy social_content_assets_admin_all
on public.social_content_assets for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy social_reels_admin_all
on public.social_reels for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy social_reel_frames_admin_all
on public.social_reel_frames for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy social_post_history_admin_all
on public.social_post_history for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

insert into public.social_content_items
(id,program,campaign,campaign_day,title,audience,goal,purpose,primary_message,caption,cta,format,status,notes)
values
('RRL-01','Rebel Ranch Local','2026-08 Launch',1,'What is Rebel Ranch Local?','Everyone','Awareness','Explain the umbrella quickly: Marketplace, Goods and Services in one easier local starting point.','Local food, handmade goods and local services are easier to find when the community has one place to start.','Local food. Local goods. Local services. One easy place.\n\nRebel Ranch Ministries built Rebel Ranch Local to make it easier to find what our own community already grows, makes, sells and does.','Follow and share','Reel + Standalone','Needs Review','Use as the campaign introduction / umbrella explainer.'),
('RRL-02','Rebel Ranch Local','2026-08 Launch',2,'Tired of Hunting All Over for Local?','Buyers','Problem recognition','Make people recognize the frustration before introducing the solution.','Facebook posts disappear. Vendors are hard to find again. Local services are scattered. Big business gets most of the attention.','You saw it last week. Now you cannot find the post. You met the seller at a festival. Now you cannot remember their name. You know someone local does the work — but who?\n\nThat is exactly the problem Rebel Ranch Ministries is trying to make easier.','Comment if this happens to you','Reel + Standalone','Visual Ready','Problem / need campaign lane.'),
('RRL-03','Rebel Ranch Local','2026-08 Launch',3,'What Do You Want to Find Locally?','Community','Comments / research','Collect real market intelligence while giving the community a voice in what gets built and promoted.','Ask what people want, what is missing locally and what they would actually use.','We are building this for the community — so tell us what YOU actually want to find locally.\n\nFood? A service? Something handmade? A person with a skill you can never seem to find when you need them?','Tell us what is missing','Reel + Standalone','Needs Review','Community-input campaign lane.'),
('RRL-04','Rebel Ranch Local','2026-08 Launch',4,'Why Sellers Should Join','Sellers / Providers','Seller recruitment','Recruit local supply before sending heavy buyer traffic.','Free participation, no marketplace commission, easier discovery and direct connection with buyers.','If you grow it, make it, sell it or provide the service locally, people should be able to find you.\n\nRebel Ranch Local is free for approved sellers and providers. Rebel Ranch Ministries does not take a marketplace commission on your sale.','Tag a local seller or provider','Reel + Standalone','Needs Review','Seller-benefit campaign lane.'),
('RRL-05','Rebel Ranch Local','2026-08 Launch',5,'Why Buyers Use It','Buyers','Buyer interest','Show the convenience of finding local food, goods and services without chasing scattered posts.','One local starting point instead of random social posts, forgotten vendor names and scattered service searches.','Want to buy local but tired of hunting for it?\n\nRebel Ranch Local is being built as one easier starting point for local food, handmade goods and people you can actually hire.','Share with someone who buys local','Reel + Standalone','Needs Review','Buyer-benefit campaign lane.'),
('RRL-06','Rebel Ranch Local','2026-08 Launch',6,'Marketplace Spotlight','Growers / Food Sellers','Category education','Make the food and farm side immediately understandable.','Meat, produce, raw milk, honey, canned goods and other legitimate local food offerings.','Meat. Produce. Raw milk. Honey. Canned goods. Local food should not be harder to find than the big-box version.','What would you search for first?','Reel + Standalone','Visual Ready','Latest campaign visual exists.'),
('RRL-07','Rebel Ranch Local','2026-08 Launch',7,'Why Rebel Ranch Ministries Built It','Everyone','Trust / mission','Connect the product to the larger community mission without turning it into an institutional ad.','Reconnect people with useful skills, products, services and opportunity already present in their own community.','Strong communities used to know who grew the food, who made things and who could fix what was broken.\n\nRebel Ranch Ministries is building Rebel Ranch Local to make those connections easier again.','Follow the mission','Reel + Standalone','Visual Ready','Latest campaign visual exists.'),
('RRL-08','Rebel Ranch Local','2026-08 Launch',8,'Goods Spotlight','Makers','Category education','Show that locally made goods have their own clear place in the system.','Candles, soap, tinctures, crafts and other legitimate handmade or local products.','Somebody local is already making something worth finding.\n\nCandles. Soap. Tinctures. Crafts. Handmade goods.','Tag a local maker','Reel + Standalone','Visual Ready','Latest campaign visual exists.'),
('RRL-09','Rebel Ranch Local','2026-08 Launch',9,'Services Spotlight','Service Providers','Category education','Break the assumption that Marketplace means food only.','Trades, repairs, lawn care, cleaning and other useful local service providers belong in the local system too.','Buying local is not only about food.\n\nWho fixes it? Builds it? Cleans it? Repairs it? Maintains it?\n\nRebel Ranch Local includes local services and trades too.','What service is hardest to find?','Reel + Standalone','Visual Ready','Latest campaign visual exists.'),
('RRL-10','Rebel Ranch Local','2026-08 Launch',10,'How Sellers Join','Sellers / Providers','Registration','Remove uncertainty about the seller path.','Apply → get approved → build the listing/storefront → show products or services → connect directly with buyers.','Want to be found locally?\n\nApply. Get approved. Build your listing. Show what you sell or do. Connect directly with buyers.\n\nNo marketplace membership fee.','Start your seller application','Reel','Visual Ready','Concept visual exists. Final reel should include real Marketplace account/dashboard screenshots.'),
('RRL-11','Rebel Ranch Local','2026-08 Launch',11,'How Buyers Use It','Buyers','Usage','Show the shortest path from a need to a local person or product.','Browse or search → choose Marketplace, Goods or Services → find a seller/provider → connect directly.','Need something local? Start in one place. Browse the category you need, find the local seller or provider, then connect directly.','Search local','Reel','Visual Ready','Concept visual exists. Final reel should include real public directory/listing screenshots.'),
('RRL-12','Rebel Ranch Local','2026-08 Launch',12,'Why It Helps the Community','Everyone','Shares / mission','Explain the local-system benefit beyond one transaction.','Local spending supports small operators, keeps more activity close to home and helps useful community relationships become easier to maintain.','Every local connection matters. Finding the grower, maker, seller or skilled person nearby is not only convenient — it helps strengthen the network we all depend on.','Share if local matters to you','Reel + Standalone','Needs Review','Community-benefit campaign lane.'),
('RRL-13','Rebel Ranch Local','2026-08 Launch',13,'Real Marketplace Proof','Everyone','Trust / product proof','Show that Rebel Ranch Local is a real usable system, not only a marketing concept.','Use actual public Marketplace, seller listing/storefront and seller dashboard screenshots.','This is not just an idea. Rebel Ranch Marketplace already gives local sellers a real place to apply, build their presence and be found.\n\nHere is what the actual system looks like.','Would you use this?','Reel','Planned','Do not use fabricated interface images. Real screenshots only.'),
('RRL-14','Rebel Ranch Local','2026-08 Launch',14,'One Place for Local — Launch Roundup','Everyone','Conversion','Close the launch sequence by tying Marketplace, Goods, Services, seller participation and buyer use together.','Marketplace • Goods • Services. One easier local starting point, built by Rebel Ranch Ministries.','Food. Handmade goods. Useful services. Local people already have so much of what the community needs. Rebel Ranch Local makes those connections easier to find and keep.','Use one campaign-specific CTA when posting','Reel','Planned','Build only after proof frames and core visuals are approved.')
on conflict (id) do nothing;

insert into public.social_content_assets
(content_item_id,asset_kind,asset_status,master_filename,external_archive_path,notes)
values
('RRL-01','image','Needs Review','rebel_ranch_local_marketplace_poster.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Launch-foundation support visual; final intro selection still needs review.'),
('RRL-06','image','Visual Ready','rebel_ranch_marketplace_spotlight.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Marketplace category spotlight.'),
('RRL-07','image','Visual Ready','rebel_ranch_local_marketplace_mission.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Why Rebel Ranch Ministries built it.'),
('RRL-08','image','Visual Ready','rebel_ranch_local_goods_spotlight.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Goods category spotlight.'),
('RRL-09','image','Visual Ready','rebel_ranch_local_services_spotlight.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Services category spotlight.'),
('RRL-10','image','Visual Ready','rebel_ranch_seller_marketplace_infographic.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Seller how-to concept; real-app screenshots still required for final proof reel.'),
('RRL-11','image','Visual Ready','rebel_ranch_local_marketplace_guide.png','F:\\Rebel Ranch Ministries\\Programs\\Marketplace\\Assets\\images','Buyer how-to concept; real public screenshots still required for final proof reel.');
