-- AI-Agent: Claude Code (Claude Opus 5.5)
-- Session: Social Content Hub — verify system + all-programs full-control v2 (2026-09-25)
-- Purpose: Owner-editable partner research lists (service area, prospect types, needs list) with
-- priorities, reusable partnership templates, the owner-approved fit-scoring rules, and a wider
-- research focus that includes small local businesses, farms and makers. Additive only.

create table if not exists public.social_service_areas (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  kind text not null default 'Town' check (kind in ('County','City','Town','Region')),
  county text,
  priority text not null default 'Medium' check (priority in ('High','Medium','Low')),
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_prospect_types (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  examples text,
  priority text not null default 'Medium' check (priority in ('High','Medium','Low')),
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_needs (
  id bigint generated by default as identity primary key,
  item text not null check (length(btrim(item)) > 0),
  category text,
  program_id bigint references public.social_programs(id) on delete set null,
  priority text not null default 'Medium' check (priority in ('High','Medium','Low')),
  progress text not null default 'Needed' check (progress in ('Needed','Partly met','Met')),
  quantity text,
  likely_sources text,
  est_value text,
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists social_needs_program_id_idx on public.social_needs(program_id);

create table if not exists public.social_templates (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  kind text not null default 'First outreach'
    check (kind in ('First outreach','Follow-up','Reply','Thank you','Sponsor benefits','Other')),
  category text not null default 'Any',
  subject text,
  body text not null,
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array['social_service_areas','social_prospect_types','social_needs','social_templates']
  loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function private.set_updated_at()', t || '_set_updated_at', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon', t);
    execute format('revoke all on table public.%I from authenticated', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
    execute format('grant usage, select on sequence public.%I to authenticated', t || '_id_seq');
    execute format('drop policy if exists %I on public.%I', t || '_admin_all', t);
    execute format('create policy %I on public.%I for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))', t || '_admin_all', t);
  end loop;
end $$;

-- Service area
insert into public.social_service_areas (name, kind, county, priority, notes) values
('Gilchrist County','County','Gilchrist','High','Home county.'),
('Trenton','Town','Gilchrist','High',null),
('Bell','Town','Gilchrist','High',null),
('Fanning Springs','Town','Gilchrist / Levy','Medium',null),
('Alachua County','County','Alachua','High','Largest nearby market (~290,000 people).'),
('Gainesville','City','Alachua','High','Biggest city in the area — lots of small businesses, farms nearby, banks, civic clubs.'),
('Newberry','Town','Alachua','High',null),
('Jonesville','Town','Alachua','High',null),
('Alachua (city)','City','Alachua','Medium',null),
('High Springs','Town','Alachua','Medium',null),
('Archer','Town','Alachua','Medium',null),
('Levy County','County','Levy','Medium',null),
('Chiefland','Town','Levy','Medium',null),
('Williston','Town','Levy','Medium',null),
('Bronson','Town','Levy','Low',null),
('Dixie County','County','Dixie','Low',null),
('Cross City','Town','Dixie','Low',null)
on conflict (name) do nothing;

-- Prospect types (small/local first)
insert into public.social_prospect_types (name, examples, priority) values
('Small local businesses & shops','Boutiques, hardware stores, pharmacies, gift shops, salons, thrift stores','High'),
('Farms, ranches & growers','Family farms, cattle/hog operations, produce growers, nurseries, U-pick farms, beekeepers','High'),
('Feed stores & farm supply','Independent feed & seed stores, co-ops, Tractor Supply stores','High'),
('Makers & home-based businesses','Bakers, soap/candle makers, woodworkers, crafters, cottage food','High'),
('Restaurants, cafés & food trucks','Local diners, BBQ, coffee shops, food trucks','Medium'),
('Trades & contractors','Fencing, welding, construction, landscaping, electricians, well/pump','Medium'),
('Churches & ministries','Local churches, youth groups, church outreach funds','Medium'),
('Civic clubs & service groups','Rotary, Lions, Kiwanis, Woman''s Club, Farm Bureau chapters','Medium'),
('Banks & credit unions','Community banks and credit unions with local giving','Medium'),
('Vehicle & equipment dealers','Truck/auto dealers, tractor/ATV/UTV dealers, equipment rental','Medium'),
('Homeschool groups & co-ops','Homeschool co-ops, family learning groups (Creation Station, Academy)','Medium'),
('Chambers & business associations','Chambers of commerce, merchant associations','Low'),
('Agencies & extension offices','UF/IFAS Extension, 4-H, soil & water districts','Low'),
('Larger regional companies','Regional chains, utilities, larger employers with community programs','Low')
on conflict (name) do nothing;

-- Needs list imported from marketing/partner-outreach/in-kind-needs-list.md (priorities were all Unset → Medium)
insert into public.social_needs (item, category, program_id, likely_sources)
select v.item, v.category, (select id from public.social_programs where code = 'RBAP'), v.src
from (values
('T-posts','Fencing & Enclosure','Tractor Supply, feed stores'),
('Field/woven wire fencing','Fencing & Enclosure','Tractor Supply, feed stores'),
('Hog/cattle panels','Fencing & Enclosure','Tractor Supply, feed stores'),
('Gates (walk-through and drive-through)','Fencing & Enclosure','Tractor Supply, feed stores'),
('Fence staples, wire, stretcher tools','Fencing & Enclosure','Tractor Supply, feed stores'),
('Pig feed','Feed','Feed stores, farms'),
('Chicken feed (layer + chick starter)','Feed','Feed stores, farms'),
('Rabbit pellets','Feed','Feed stores'),
('Guinea fowl / game bird feed','Feed','Feed stores'),
('Dog food (guardian dogs)','Feed','Feed stores, pet stores'),
('Hay (bedding/supplemental)','Feed','Local hay farms, feed stores'),
('Mineral/salt blocks','Feed','Feed stores'),
('Water troughs','Watering','Feed stores, farm supply'),
('Stock tanks','Watering','Feed stores, farm supply'),
('Automatic poultry waterers','Watering','Feed stores'),
('Rabbit water bottle/nipple systems','Watering','Feed stores'),
('Hose/plumbing for pen water lines','Watering','Hardware stores, plumbers'),
('Poultry feeders','Feeders','Feed stores'),
('Pig feeders/troughs','Feeders','Feed stores, welders'),
('Rabbit feeders','Feeders','Feed stores'),
('Hay racks','Feeders','Feed stores, welders'),
('Truck (hauling feed/supplies/animals)','Vehicles & Equipment','Truck dealers'),
('Side-by-side/UTV','Vehicles & Equipment','ATV/UTV dealers'),
('Livestock or utility trailer','Vehicles & Equipment','Trailer/truck dealers'),
('Generator','Vehicles & Equipment','Equipment rental, hardware stores'),
('Hand tools (wheelbarrow, shovels, post driver, fence stretcher)','Vehicles & Equipment','Hardware stores, feed stores'),
('Coop-building materials (lumber, hardware cloth, roofing)','Shelter & Housing','Lumber yards, hardware stores, contractors'),
('Shade structures','Shelter & Housing','Contractors, farm supply'),
('Rabbit hutches','Shelter & Housing','Feed stores, woodworkers'),
('Heat lamps/brooders for chicks','Shelter & Housing','Feed stores'),
('Tarps','General','Hardware stores'),
('Basic animal first-aid/vet supplies','General','Feed stores, vets'),
('Cleaning/sanitation supplies','General','Hardware stores, janitorial suppliers')
) as v(item, category, src)
where not exists (select 1 from public.social_needs n where n.item = v.item);

-- Templates. Placeholders in {{double braces}} are filled from the prospect when used in the Hub.
insert into public.social_templates (name, kind, category, subject, body, notes) values
('Partnership introduction — local business','First outreach','Any',
 $t$Partnering with Rebel Ranch Ministries$t$,
 $t$Hi {{contact_first_name}},

I'm Brooke with Rebel Ranch Ministries here in {{area}}. We're a local nonprofit — a ministry of Faith, Family, and Nature Church — building real, hands-on programs for our community: creative sessions for kids, farm and animal care, real-life skills, a free local marketplace for small businesses and growers, and practical help for small business owners.

We're looking for local businesses to partner with, and {{business_name}} came to mind because {{why_them}}.

Ways to partner:
• Donate goods or supplies (right now we could really use {{specific_need}})
• Sponsor a program, a project, or an animal
• Make a one-time or monthly gift
• Team up on something that sends local customers your way

What your business gets:
• A tax-deductible gift — we're a tax-exempt church nonprofit, and we send you a written receipt for your records
• A public thank-you and recognition as a community partner on our Facebook, Instagram, and website
• A spotlight post introducing {{business_name}} to local families
• The goodwill that comes from backing something real, right here at home

Could we set up a quick call? Just reply to this email and I'll work around your schedule.

Thank you for what you do for {{area}}.$t$,
 'General-purpose first email. Swap the "Ways to partner" bullets to fit the prospect.'),
('In-kind supplies request — farm & feed','First outreach','B — Service/resource exchange',
 $t$Could {{business_name}} help us with {{specific_need}}?$t$,
 $t$Hi {{contact_first_name}},

I'm Brooke with Rebel Ranch Ministries, a local nonprofit ministry of Faith, Family, and Nature Church in {{area}}. Our Roots, Boots & Animal Poops program teaches kids and families real farm and animal-care skills, and our Rebel Ranch Rescue program takes in farm animals that need a second chance.

We're building out the operation and could really use {{specific_need}}. Any donation — full, partial, or a discount — makes a real difference.

In return:
• Your donation is tax-deductible, and we'll send a written receipt for your records
• We'll thank {{business_name}} publicly as a supporting partner on our social media and website
• We'll send the families in our programs your way for their own supplies

Would you be open to talking about it? Reply here anytime.

Thank you — local businesses like yours are what make this possible.$t$,
 'For feed stores, farm supply, hardware, farms, trades.'),
('Friendly follow-up','Follow-up','Any',
 $t$Re: Partnering with Rebel Ranch Ministries$t$,
 $t$Hi {{contact_first_name}},

Just circling back on my note about partnering with Rebel Ranch Ministries. I know things get busy — no pressure at all.

If it helps, even a small donation of {{specific_need}} or a quick conversation about ideas would mean a lot. Donations are tax-deductible and we always send a receipt.

Happy to answer any questions. Thanks for considering it!$t$,
 'Use about a week after the first message. Max two follow-ups.'),
('Thank you for your gift','Thank you','Any',
 $t$Thank you from Rebel Ranch Ministries$t$,
 $t$Hi {{contact_first_name}},

Thank you so much for {{gift_description}}. It's going straight to work in our programs, and it truly makes a difference for the kids, families, and animals we serve.

Your written donation receipt is attached for your records. We'd love to thank {{business_name}} publicly on our Facebook and Instagram — just let me know if you'd rather we didn't, or if there's a photo or link you'd like us to use.

With gratitude,$t$,
 'Send after a gift is received. Attach the receipt from the Donations Received tool.')
on conflict (name) do nothing;

-- Owner-approved fit scoring + wider research focus
insert into public.social_settings (key, value, label, description, sort_order) values
('partner_qualification_rules',$s$MUST-HAVES (skip the prospect if any is missing):
1. Inside an Active service area (Setup → Service area).
2. Reachable by email, phone, Facebook message or web form — no in-person visit required.
3. Does not require a 501(c)(3) determination letter or Deed verification (those belong in the grants pipeline).

FIT SCORE (1 point each, 5 max):
• Need match — they sell, make or do something on the Needs list, or clearly fit one program.
• Proof they give — community giving program, sponsors local causes (4-H, schools, churches), or have donated before.
• Reachable decision-maker — a named owner/manager, or a local store that handles its own donations (not a corporate portal).
• Two-way value — they get something real back (customers, visibility, families referred to them).
• Warm connection — local/family-owned, active in the community or churches, or a known connection.

ALWAYS RULE OUT: anything tied to 3P Help Me; festival vendor/booth asks; anything requiring the owner to show up in person.

MIX: every run, at least half of new prospects must come from High-priority prospect types (small local businesses, farms, makers, feed stores) — not only banks and large organizations.$s$,
 'Qualification rules','How the agent decides who is a good prospect and scores fit 1–5. Edit anytime.',45)
on conflict (key) do nothing;

update public.social_settings set value = $s$Cast a wide net across the Active service area (Setup → Service area), highest priority first — Gilchrist County, Gainesville, Newberry and the rest of Alachua County, then Levy and Dixie. Look through the Active prospect types (Setup → Prospect types), highest priority first: small local businesses, family farms and growers, feed stores, makers and home businesses — plus larger organizations like banks, civic clubs and dealers. Match them to items on the Needs list (Setup → Needs list, High priority first) and to program fits (Creation Station, Marketplace, Academy, Business Freedom, Roots Boots & Animal Poops, Rebel Ranch Rescue). Small and local is just as valuable as big.$s$
where key = 'partner_research_focus';

insert into public.social_activity_log (entity_type, entity_id, action, detail, actor, user_id)
values ('system', null, 'Partner lists + templates installed',
        'Service area (17), prospect types (14), needs list (33, from in-kind-needs-list.md), 4 partnership templates, qualification rules, wider research focus.', 'Claude', null);
