-- AI-Agent: Claude Code (Claude Opus 5.5)
-- Session: Social Content Hub — verify system + all-programs full-control v2 (2026-09-25)
-- Purpose: Stage 1 partnership pipeline. Prospects found by the research agent are reviewed by the
-- owner, drafts and suggested replies live in a per-prospect conversation thread with their own
-- review status, and owner-editable settings control the agent. Nothing here sends email.
-- Additive only. Owner-authorized in chat 2026-09-25.

-- 1. Pipeline statuses + prospect research fields
alter table public.social_outreach drop constraint if exists social_outreach_status_check;
alter table public.social_outreach add constraint social_outreach_status_check
  check (status in ('Prospect','Prospect Approved','Researched','Draft','Needs Edit','Approved','Sent',
                    'Replied','Follow-Up','In Conversation','Partner','Declined','Rejected','Archived'));

alter table public.social_outreach
  add column if not exists fit_reason text,
  add column if not exists fit_score integer check (fit_score is null or fit_score between 1 and 5),
  add column if not exists county text,
  add column if not exists sources text,
  add column if not exists found_by text,
  add column if not exists last_contact_at timestamptz,
  add column if not exists last_inbound_at timestamptz;

-- 2. Conversation thread per prospect
create table if not exists public.social_outreach_messages (
  id bigint generated by default as identity primary key,
  outreach_id bigint not null references public.social_outreach(id) on delete cascade,
  direction text not null default 'Outbound' check (direction in ('Outbound','Inbound')),
  channel text not null default 'Email'
    check (channel in ('Email','Facebook message','Phone call','Web form','In person','Text','Other')),
  from_address text,
  to_address text,
  subject text,
  body text,
  status text not null default 'Suggested'
    check (status in ('Suggested','Needs Edit','Approved','Sent','Received','Rejected','Logged')),
  suggested_by text,
  owner_comment text,
  approved_at timestamptz,
  sent_at timestamptz,
  received_at timestamptz,
  external_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists social_outreach_messages_outreach_idx on public.social_outreach_messages(outreach_id, created_at);
create index if not exists social_outreach_messages_status_idx on public.social_outreach_messages(status);
create unique index if not exists social_outreach_messages_external_ref_uniq
  on public.social_outreach_messages(external_ref) where external_ref is not null;

drop trigger if exists social_outreach_messages_set_updated_at on public.social_outreach_messages;
create trigger social_outreach_messages_set_updated_at before update on public.social_outreach_messages
for each row execute function private.set_updated_at();

-- 3. Owner-editable settings
create table if not exists public.social_settings (
  key text primary key check (key ~ '^[a-z0-9_]+$'),
  value text,
  label text,
  description text,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);
drop trigger if exists social_settings_set_updated_at on public.social_settings;
create trigger social_settings_set_updated_at before update on public.social_settings
for each row execute function private.set_updated_at();

-- 4. Security: administrators only
do $$
declare t text;
begin
  foreach t in array array['social_outreach_messages','social_settings']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon', t);
    execute format('revoke all on table public.%I from authenticated', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_all', t);
    execute format('create policy %I on public.%I for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))', t || '_admin_all', t);
  end loop;
end $$;
grant usage, select on sequence public.social_outreach_messages_id_seq to authenticated;

-- 5. Settings seed
insert into public.social_settings (key, value, label, description, sort_order) values
('outreach_from_address','partners@ffnchurch.org','Outreach email address','The address partnership emails are sent from and replies come back to (Proton).',10),
('outreach_signature',$s$Brooke
Rebel Ranch Ministries
A ministry of Faith, Family, and Nature Church
partners@ffnchurch.org · rebelranchministries.org$s$,'Email signature','Added to the end of every outreach email.',20),
('partner_agent_enabled','true','Partnership agent on','true = the daily partnership agent runs; false = it skips every run until turned back on.',30),
('partner_research_per_run','5','New prospects per run','How many new prospects the agent researches each run (0 = research paused).',40),
('partner_research_focus',$s$Local businesses, civic clubs, churches, farms/feed stores, banks and agencies in Gilchrist, Alachua (Newberry, High Springs, Alachua, Gainesville), Levy and Dixie counties that fit a current program need (see the in-kind needs list) or could sponsor/align with Creation Station, Marketplace, Academy, Business Freedom, Roots Boots & Animal Poops, or Rebel Ranch Rescue. Phone/email/online contact only (limited transportation). No festival vendor/booth asks.$s$,'Research focus','What the agent should look for. Edit anytime.',50),
('partner_followup_days','7','Follow-up after (days)','Default days after sending before a follow-up is due.',60)
on conflict (key) do nothing;

-- 6. Move existing draft messages into threads (first outbound message per prospect)
insert into public.social_outreach_messages (outreach_id, direction, channel, to_address, subject, body, status, suggested_by, created_at)
select o.id, 'Outbound',
       case when o.contact_method ilike '%facebook%' then 'Facebook message'
            when o.contact_method ilike '%phone%' then 'Phone call'
            when o.contact_method ilike '%form%' then 'Web form'
            else 'Email' end,
       o.contact_email, o.subject, o.message,
       case o.status when 'Needs Edit' then 'Needs Edit' when 'Rejected' then 'Rejected' when 'Approved' then 'Approved' when 'Sent' then 'Sent' else 'Suggested' end,
       'Claude (2026-08 outreach batch)', o.created_at
from public.social_outreach o
where o.message is not null
  and not exists (select 1 from public.social_outreach_messages m where m.outreach_id = o.id);

insert into public.social_activity_log (entity_type, entity_id, action, detail, actor, user_id)
values ('system', null, 'Partnership pipeline installed',
        'Prospect review stages, conversation threads with per-message review, owner settings (from partners@ffnchurch.org).', 'Claude', null);
