-- AI-Agent: Claude Code (Claude Opus 5.5)
-- Session: Social Content Hub — verify system + all-programs full-control v2 (2026-09-25)
-- Purpose: Turn the v1 (Rebel Ranch Local-only) Social Content Hub into the owner's full
-- control panel for every Rebel Ranch Ministries program and purpose: owner-managed
-- programs, purposes, campaigns, links and channels; scheduling; ChatGPT image handoff;
-- dashboard image uploads; partner outreach; results; learning loop; activity log.
-- Additive only: no v1 column, row or policy is dropped. Owner-authorized in chat 2026-09-25.

-- ---------------------------------------------------------------------------
-- 1. Owner-managed lists
-- ---------------------------------------------------------------------------
create table if not exists public.social_programs (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  code text not null unique check (code ~ '^[A-Z0-9]{2,6}$'),
  description text,
  default_link text check (default_link is null or default_link ~* '^https?://'),
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  sort_order integer not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_purposes (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  description text,
  weekly_limit integer check (weekly_limit is null or weekly_limit >= 0),
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  sort_order integer not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  label text not null check (length(btrim(label)) > 0),
  url text not null check (url ~* '^https?://'),
  program_id bigint references public.social_programs(id) on delete set null,
  purpose_id bigint references public.social_purposes(id) on delete set null,
  status text not null default 'Active' check (status in ('Active','Retired')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_channels (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  platform text not null default 'Facebook'
    check (platform in ('Facebook','Instagram','YouTube','TikTok','X','LinkedIn','Pinterest','Nextdoor','Email','Website','Other')),
  kind text not null default 'Page'
    check (kind in ('Page','Group','Profile','Account','Email List','Other')),
  url text check (url is null or url ~* '^https?://'),
  posting_rules text,
  status text not null default 'Active' check (status in ('Active','Paused','Archived')),
  sort_order integer not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_campaigns (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  program_id bigint references public.social_programs(id) on delete set null,
  purpose_id bigint references public.social_purposes(id) on delete set null,
  link_id bigint references public.social_links(id) on delete set null,
  goal text,
  start_date date,
  end_date date,
  status text not null default 'Planned'
    check (status in ('Planned','Active','Paused','Completed','Archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

-- ---------------------------------------------------------------------------
-- 2. Content items: references, scheduling, image workflow, control fields
-- ---------------------------------------------------------------------------
alter table public.social_content_items
  add column if not exists program_id bigint references public.social_programs(id),
  add column if not exists purpose_id bigint references public.social_purposes(id) on delete set null,
  add column if not exists campaign_id bigint references public.social_campaigns(id) on delete set null,
  add column if not exists link_id bigint references public.social_links(id) on delete set null,
  add column if not exists link_url text check (link_url is null or link_url ~* '^https?://'),
  add column if not exists channel_ids bigint[] not null default '{}',
  add column if not exists scheduled_for timestamptz,
  add column if not exists image_needed boolean not null default true,
  add column if not exists image_prompt text,
  add column if not exists image_status text not null default 'Prompt Needed'
    check (image_status in ('Not Needed','Prompt Needed','Ready for Image','Generating','Needs Review','Revision Needed','Approved')),
  add column if not exists hashtags text,
  add column if not exists assigned_to text not null default 'Unassigned'
    check (assigned_to in ('Unassigned','Owner','Claude','ChatGPT','Other')),
  add column if not exists is_paused boolean not null default false,
  add column if not exists priority integer not null default 3 check (priority between 1 and 5),
  add column if not exists source_ref text;

alter table public.social_content_items drop constraint if exists social_content_items_status_check;
alter table public.social_content_items add constraint social_content_items_status_check
  check (status in ('Idea','Draft','Planned','Needs Review','Needs Edit','Visual Ready','Approved','Scheduled','Posted','Rejected','Archived'));
alter table public.social_content_items alter column status set default 'Draft';

alter table public.social_content_items drop constraint if exists social_content_items_format_check;
alter table public.social_content_items add constraint social_content_items_format_check
  check (format in ('Reel','Standalone','Reel + Standalone','Carousel','Story','Text Only','Video'));

create sequence if not exists public.social_content_item_seq start with 100;

-- Keeps the legacy program/campaign text columns in step with the managed lists and
-- gives new items an ID like "CS-0101" (program code + number) when none is supplied.
create or replace function private.social_content_items_prepare()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_code text;
  v_name text;
  v_campaign text;
begin
  if new.program_id is not null then
    select p.code, p.name into v_code, v_name from public.social_programs p where p.id = new.program_id;
    new.program := v_name;
  end if;
  if new.program is null or btrim(new.program) = '' then
    new.program := 'Unassigned';
  end if;

  if new.campaign_id is not null then
    select c.name into v_campaign from public.social_campaigns c where c.id = new.campaign_id;
    new.campaign := v_campaign;
  elsif (tg_op = 'UPDATE' and old.campaign_id is not null) or new.campaign is null or btrim(new.campaign) = '' then
    new.campaign := 'General';
  end if;

  if new.id is null or btrim(new.id) = '' then
    new.id := coalesce(v_code, 'SC') || '-' || lpad(nextval('public.social_content_item_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists social_content_items_prepare on public.social_content_items;
create trigger social_content_items_prepare
before insert or update on public.social_content_items
for each row execute function private.social_content_items_prepare();

create or replace function private.social_programs_propagate_name()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.name is distinct from old.name then
    update public.social_content_items set program = new.name where program_id = new.id;
    update public.social_reels set program = new.name where program = old.name;
  end if;
  return new;
end;
$$;

create or replace function private.social_campaigns_propagate_name()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.name is distinct from old.name then
    update public.social_content_items set campaign = new.name where campaign_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists social_programs_propagate_name on public.social_programs;
create trigger social_programs_propagate_name
after update of name on public.social_programs
for each row execute function private.social_programs_propagate_name();

drop trigger if exists social_campaigns_propagate_name on public.social_campaigns;
create trigger social_campaigns_propagate_name
after update of name on public.social_campaigns
for each row execute function private.social_campaigns_propagate_name();

-- ---------------------------------------------------------------------------
-- 3. Assets uploaded from the dashboard + posting results
-- ---------------------------------------------------------------------------
alter table public.social_content_assets
  add column if not exists storage_path text;

alter table public.social_post_history
  add column if not exists channel_id bigint references public.social_channels(id) on delete set null,
  add column if not exists post_status text not null default 'Published'
    check (post_status in ('Scheduled','Published','Failed','Removed')),
  add column if not exists posted_by text,
  add column if not exists reach integer check (reach is null or reach >= 0),
  add column if not exists reactions integer check (reactions is null or reactions >= 0),
  add column if not exists comments integer check (comments is null or comments >= 0),
  add column if not exists shares integer check (shares is null or shares >= 0),
  add column if not exists clicks integer check (clicks is null or clicks >= 0),
  add column if not exists metrics_updated_at timestamptz;

-- ---------------------------------------------------------------------------
-- 4. Outreach, learning loop, activity log
-- ---------------------------------------------------------------------------
create sequence if not exists public.social_outreach_ref_seq start with 14;

create table if not exists public.social_outreach (
  id bigint generated by default as identity primary key,
  ref text not null unique default ('OUT-' || lpad(nextval('public.social_outreach_ref_seq')::text, 3, '0')),
  target_name text not null check (length(btrim(target_name)) > 0),
  category text not null default 'General alignment'
    check (category in ('A — Fund request','B — Service/resource exchange','C — Reduced/free service RRM provides','General alignment','Program affiliation','Other')),
  target_type text,
  program_id bigint references public.social_programs(id) on delete set null,
  purpose_id bigint references public.social_purposes(id) on delete set null,
  campaign_id bigint references public.social_campaigns(id) on delete set null,
  contact_method text,
  contact_name text,
  contact_email text,
  contact_phone text,
  website text,
  contact_details text,
  offer_ask text,
  subject text,
  message text,
  status text not null default 'Researched'
    check (status in ('Researched','Draft','Needs Edit','Approved','Sent','Replied','Follow-Up','Declined','Rejected','Archived')),
  is_paused boolean not null default false,
  assigned_to text not null default 'Unassigned'
    check (assigned_to in ('Unassigned','Owner','Claude','ChatGPT','Other')),
  follow_up_on date,
  sent_at timestamptz,
  sent_by text,
  response text,
  time_sensitivity text,
  research_needed text,
  notes text,
  source_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_learnings (
  id bigint generated by default as identity primary key,
  title text not null check (length(btrim(title)) > 0),
  observation text,
  evidence text,
  recommendation text,
  program_id bigint references public.social_programs(id) on delete set null,
  purpose_id bigint references public.social_purposes(id) on delete set null,
  status text not null default 'Proposed'
    check (status in ('Proposed','Approved','Applied','Rejected','Noted')),
  recorded_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_activity_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null,
  detail text,
  actor text not null default 'Owner',
  user_id uuid default auth.uid(),
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 5. Indexes, updated_at triggers
-- ---------------------------------------------------------------------------
create index if not exists social_content_items_program_id_idx on public.social_content_items(program_id);
create index if not exists social_content_items_purpose_id_idx on public.social_content_items(purpose_id);
create index if not exists social_content_items_campaign_id_idx on public.social_content_items(campaign_id);
create index if not exists social_content_items_link_id_idx on public.social_content_items(link_id);
create index if not exists social_content_items_scheduled_idx on public.social_content_items(scheduled_for);
create index if not exists social_links_program_id_idx on public.social_links(program_id);
create index if not exists social_links_purpose_id_idx on public.social_links(purpose_id);
create index if not exists social_campaigns_program_id_idx on public.social_campaigns(program_id);
create index if not exists social_campaigns_purpose_id_idx on public.social_campaigns(purpose_id);
create index if not exists social_campaigns_link_id_idx on public.social_campaigns(link_id);
create index if not exists social_post_history_channel_id_idx on public.social_post_history(channel_id);
create index if not exists social_outreach_program_id_idx on public.social_outreach(program_id);
create index if not exists social_outreach_purpose_id_idx on public.social_outreach(purpose_id);
create index if not exists social_outreach_campaign_id_idx on public.social_outreach(campaign_id);
create index if not exists social_outreach_status_idx on public.social_outreach(status);
create index if not exists social_learnings_program_id_idx on public.social_learnings(program_id);
create index if not exists social_learnings_purpose_id_idx on public.social_learnings(purpose_id);
create index if not exists social_activity_log_created_idx on public.social_activity_log(created_at desc);

do $$
declare t text;
begin
  foreach t in array array['social_programs','social_purposes','social_links','social_channels','social_campaigns','social_outreach','social_learnings']
  loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function private.set_updated_at()', t || '_set_updated_at', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 6. Security: administrators only (RLS + explicit grants; anon gets nothing)
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['social_programs','social_purposes','social_links','social_channels','social_campaigns','social_outreach','social_learnings']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon', t);
    execute format('revoke all on table public.%I from authenticated', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_all', t);
    execute format('create policy %I on public.%I for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))', t || '_admin_all', t);
  end loop;
end $$;

alter table public.social_activity_log enable row level security;
revoke all on table public.social_activity_log from anon;
revoke all on table public.social_activity_log from authenticated;
grant select, insert on table public.social_activity_log to authenticated;
drop policy if exists social_activity_log_admin_select on public.social_activity_log;
create policy social_activity_log_admin_select on public.social_activity_log
  for select to authenticated using ((select private.is_admin()));
drop policy if exists social_activity_log_admin_insert on public.social_activity_log;
create policy social_activity_log_admin_insert on public.social_activity_log
  for insert to authenticated with check ((select private.is_admin()));

revoke all on sequence public.social_content_item_seq from anon;
revoke all on sequence public.social_outreach_ref_seq from anon;
grant usage, select on sequence public.social_content_item_seq to authenticated;
grant usage, select on sequence public.social_outreach_ref_seq to authenticated;
grant usage, select on sequence public.social_programs_id_seq, public.social_purposes_id_seq,
  public.social_links_id_seq, public.social_channels_id_seq, public.social_campaigns_id_seq,
  public.social_outreach_id_seq, public.social_learnings_id_seq, public.social_activity_log_id_seq
  to authenticated;

-- Private storage bucket for images/videos the owner uploads from the dashboard.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('social-media', 'social-media', false, 52428800,
        array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/quicktime'])
on conflict (id) do nothing;

drop policy if exists social_media_admin_select on storage.objects;
create policy social_media_admin_select on storage.objects for select to authenticated
  using (bucket_id = 'social-media' and (select private.is_admin()));
drop policy if exists social_media_admin_insert on storage.objects;
create policy social_media_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'social-media' and (select private.is_admin()));
drop policy if exists social_media_admin_update on storage.objects;
create policy social_media_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'social-media' and (select private.is_admin()))
  with check (bucket_id = 'social-media' and (select private.is_admin()));
drop policy if exists social_media_admin_delete on storage.objects;
create policy social_media_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'social-media' and (select private.is_admin()));

-- ---------------------------------------------------------------------------
-- 7. Seed lists (owner can change everything from the dashboard afterwards)
-- ---------------------------------------------------------------------------
insert into public.social_programs (name, code, description, default_link, sort_order) values
('Rebel Ranch Ministries','RRM','The whole ministry: brand, mission, general updates and asks.','https://rebelranchministries.org/',10),
('Rebel Ranch Local / Marketplace','RRL','Rebel Ranch Local: Marketplace (food), Goods and Services — one local starting point.','https://rebelranchministries.org/marketplace.html',20),
('Creation Station','CS','Hands-on creative Sessions for young creators and their families.','https://rebelranchministries.org/creation.html',30),
('Rebel Ranch Academy','RRA','Real-life learning across the six Academy learning areas.','https://academy.rebelranchministries.org/',40),
('Business Freedom','BF','Practical help for small business owners and sole operators.','https://rebelranchministries.org/business-fixes.html',50),
('Roots, Boots & Animal Poops','RBAP','Hands-on agriculture and animal care program.','https://rebelranchministries.org/programs.html',60),
('Rebel Ranch Rescue','RRR','Farm-animal rescue, recovery and responsible stewardship.','https://rebelranchministries.org/programs.html',70),
('Faith, Family, and Nature Church','FFN','The church that Rebel Ranch Ministries operates under (ffnchurch.org).','https://ffnchurch.org/',80)
on conflict (name) do nothing;

insert into public.social_purposes (name, description, weekly_limit, sort_order) values
('Program Promotion','Show what a program does and who it is for.',null,10),
('Education','Teach something useful. Educate first, ask second.',null,20),
('Donations','Ask for support for the mission. Calendar rule: no more than 1 donation ask per week.',1,30),
('Fundraiser (GoFundMe)','Send people to an active fundraiser such as the GoFundMe.',null,40),
('Partnerships & Sponsors','Invite businesses and organizations to align, sponsor or donate in-kind.',null,50),
('Brand Awareness','Who Rebel Ranch Ministries is and why it exists.',null,60),
('Community Input','Ask questions, gather feedback, start real conversations.',null,70),
('Seller & Provider Recruitment','Recruit Marketplace sellers, makers and service providers.',null,80),
('Volunteers','Recruit helpers and volunteers.',null,90),
('Events & Announcements','Dates, launches and news.',null,100),
('Behind the Scenes','Real work-in-progress updates.',null,110)
on conflict (name) do nothing;

insert into public.social_channels (name, platform, kind, status, sort_order, notes) values
('Rebel Ranch Facebook Page','Facebook','Page','Active',10,'Main page. Add the page link in Setup → Channels.'),
('Rebel Ranch Instagram','Instagram','Account','Active',20,'Add the account link in Setup → Channels.'),
('Brooke — Personal Facebook','Facebook','Profile','Active',30,'Personal shout-outs only.')
on conflict (name) do nothing;

-- Facebook groups imported from marketing/social-media/group-rules.md (audited 2026-08-16).
insert into public.social_channels (name,platform,kind,url,posting_rules,status,sort_order,notes) values
($g$Jobs in Alachua Florida - Hiring in Gainesville, High Springs & Newberry.$g$,'Facebook','Group',null,$g$Group type:
Unresolved jobs / local employment group
Posting allowed:
No
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Not applicable; the exact group could not be located.
Best post style:
None
Allowed content buckets:
None until the exact group is identified
Do not post:
Do not use or substitute a similarly named group.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',200,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Alachua County Florida word of mouth - hire, fire, sell or buy$g$,'Facebook','Group',$g$https://www.facebook.com/groups/gainesvillefl.business/$g$,$g$Group type:
Public local community / business advertising
Posting allowed:
Yes
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes, for legitimate businesses
Links allowed:
No for the current workflow unless separately confirmed
Promo days or limits:
Ads for regulated work must include the required license number. Spam, scams, affiliate-style posts, and inauthentic-looking ads are removed.
Best post style:
Local resource / legitimate business ad / recommendation
Allowed content buckets:
Business Freedom / Marketplace / Local business
Do not post:
Do not post donation asks, unlicensed regulated-service ads, scams, affiliate offers, or generic promotional blasts.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',201,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Gilchrist County Informer$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1455405758124674/$g$,$g$Group type:
Private local community / county information
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community question / local update / useful program or resource information
Allowed content buckets:
Community questions / Farm updates / Marketplace / Business Freedom / Creation Station / Support the Mission
Do not post:
Do not post bullying, foul or explicit language, privacy violations, unrelated promotions, repetitive posts, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',202,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry FL Word of Mouth$g$,'Facebook','Group',$g$https://www.facebook.com/groups/378792851697750/$g$,$g$Group type:
Private local community / word of mouth
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community question / local recommendation / useful program or business information
Allowed content buckets:
Community questions / Local business recommendations / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not post unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',203,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Shop Newberry First$g$,'Facebook','Group',$g$https://www.facebook.com/groups/289244977863014/$g$,$g$Group type:
Public local business group — Newberry, South Carolina
Posting allowed:
No
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Not applicable to the Florida service area.
Best post style:
None
Allowed content buckets:
None
Do not post:
Do not use for Rebel Ranch Ministries Florida marketing.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',204,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry Florida Business Directory$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1643358052446114/$g$,$g$Group type:
Public Newberry, Florida business directory
Posting allowed:
Yes
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes
Links allowed:
No for the current workflow unless separately confirmed
Promo days or limits:
Dated offers and specials are removed after their stated date; keep entries current and local.
Best post style:
Clear local business resource / directory-style post
Allowed content buckets:
Marketplace / Business Freedom / Local business
Do not post:
Do not post donation asks, expired offers, unrelated content, or repetitive ads.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',205,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry FL Free ONLY site$g$,'Facebook','Group',$g$https://www.facebook.com/groups/746576295407795/$g$,$g$Group type:
Public free-items exchange
Posting allowed:
No for marketing
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Free items only; members should take only what they need.
Best post style:
None for routine marketing
Allowed content buckets:
None for marketing
Do not post:
Do not post business promotions, Marketplace promotions, donation links, sales, or ordinary program advertising.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',206,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry Fl Citizens$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1003176591713461/$g$,$g$Group type:
Public local community / citizens
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Local discussion / community update / useful program or business information
Allowed content buckets:
Community questions / Local discussion / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not use fake accounts or post unrelated, repetitive, deceptive, or spam-like content.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',207,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry here and Now$g$,'Facebook','Group',$g$https://www.facebook.com/groups/871059023590089/$g$,$g$Group type:
Public community group — Newberry County, South Carolina
Posting allowed:
No
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Not applicable to the Florida service area.
Best post style:
None
Allowed content buckets:
None
Do not post:
Do not use for Rebel Ranch Ministries Florida marketing.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',208,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry FL Word of Mouth - Freedom to Post Whatever$g$,'Facebook','Group',$g$https://www.facebook.com/groups/618937781038759/$g$,$g$Group type:
Public local community / open-posting name
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community discussion / local business or program information
Allowed content buckets:
Community questions / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not treat the group name as permission for spam, duplicate posts, deceptive links, or unrelated promotions.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',209,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry/Archer/Jonesville Fl. Buy sell trade swip swap$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1529139080633331/$g$,$g$Group type:
Public buy-sell-trade / local marketplace
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes only for a locally relevant item, resource, or support request
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Marketplace / local business / locally relevant resource post
Allowed content buckets:
Marketplace / Local business / Business Freedom / locally relevant Support the Mission requests
Do not post:
Do not post unrelated program content, duplicate listings, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',210,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry Whats Happening$g$,'Facebook','Group',$g$https://www.facebook.com/groups/newberrywhatshappenings/$g$,$g$Group type:
Public Newberry, Florida business-to-consumer community
Posting allowed:
No until pre-approval is completed under separate authorization
Donation posts allowed:
No
Business/program posts allowed:
Yes only after admin pre-approval
Links allowed:
No until pre-approval is completed
Promo days or limits:
Every Facebook Business Page must be pre-approved before any post. Personal posts are prohibited. Spam, scams, deceptive links, national politics, and hostile content are prohibited.
Best post style:
Pre-approved local business or community information only
Allowed content buckets:
Marketplace / Business Freedom / Local business / Local events
Do not post:
Do not post, seek pre-approval, or contact the admin without separate authorization. Do not use personal posts, donation asks, political content, scams, or unapproved business content.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',211,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry now uncensored v2.0 without the hate$g$,'Facebook','Group',$g$https://www.facebook.com/groups/281983004939731/$g$,$g$Group type:
Public community group; Florida location not confirmed
Posting allowed:
No until location is confirmed
Donation posts allowed:
No
Business/program posts allowed:
No until location is confirmed
Links allowed:
No until location is confirmed
Promo days or limits:
Service advertising is limited to once every 2-3 days. Repetitive posts are prohibited. Marketplace-style buying and selling has been banned; a Featured admin reply says local-business promotion is not included in that ban.
Best post style:
None until the service area is confirmed
Allowed content buckets:
None until location is confirmed
Do not post:
Do not use while the About section identifies Newberry County without confirming Newberry, Florida. Do not use marketplace-style sales posts or repetitive advertising.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',212,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry Uncensored$g$,'Facebook','Group',$g$https://www.facebook.com/groups/3464080367242532/$g$,$g$Group type:
Public community group — Newberry, South Carolina
Posting allowed:
No
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Not applicable to the Florida service area.
Best post style:
None
Allowed content buckets:
None
Do not post:
Do not use for Rebel Ranch Ministries Florida marketing.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',213,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Citizens of Newberry Forum$g$,'Facebook','Group',$g$https://www.facebook.com/groups/139234530063608/$g$,$g$Group type:
Public Newberry, Florida citizens forum
Posting allowed:
Yes, with limits
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes on Fridays only
Links allowed:
No except a Friday business advertisement when relevant
Promo days or limits:
Business advertising is allowed on Fridays only. No self-promotion or irrelevant links at other times. No for-sale or giveaway items and no national political posts.
Best post style:
Community-first local discussion; business promotion only on Friday
Allowed content buckets:
Community questions / Marketplace / Local business / Farm updates
Do not post:
Do not post business ads outside Friday, donation asks, irrelevant links, for-sale items, giveaways, business bashing, or national politics.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',214,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry FL Professionals$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1435710707740536/$g$,$g$Group type:
Public Newberry, Florida professional networking group
Posting allowed:
Yes, for professional resources and discussion
Donation posts allowed:
No
Business/program posts allowed:
Yes, as networking or a useful local resource
Links allowed:
No for direct promotion unless separately confirmed
Promo days or limits:
Keep content focused on professional relationships, hiring, opportunities, mentorship, guidance, and useful local resources.
Best post style:
Professional discussion / useful local resource / introduction
Allowed content buckets:
Business Freedom / Marketplace / Local business / Community questions
Do not post:
Do not use donation asks, farm-only updates, hard-sell advertising, or unrelated links.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',215,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry Local Businesses$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1397701373840402/$g$,$g$Group type:
Public Newberry, Florida local-business group; Florida location confirmed by Brooke
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
No
Business/program posts allowed:
Yes, when locally relevant and business-focused
Links allowed:
Yes, when directly relevant to the local business post
Promo days or limits:
Political, personal, and religious posts are prohibited. No promotion frequency was published; avoid duplicate blasting and check posted-archive.md before reuse.
Best post style:
Useful Newberry, Florida business resource / introduction / relevant program information
Allowed content buckets:
Marketplace / Business Freedom / Local business
Do not post:
Do not post political, personal, religious, donation, unrelated, repetitive, deceptive, or spam-like content.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',216,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Concerned Citizens of Newberry$g$,'Facebook','Group',$g$https://www.facebook.com/groups/822408347874660/$g$,$g$Group type:
Public community-support / citizens group
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly tied to a local community need and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community-support information / useful local resource / relevant nonprofit update
Allowed content buckets:
Community questions / Farm updates / Local support / Creation Station / Support the Mission
Do not post:
Do not post unrelated sales content, repetitive donation asks, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',217,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Newberry, Florida Happenings$g$,'Facebook','Group',$g$https://www.facebook.com/groups/930966240922279/$g$,$g$Group type:
Public Newberry, Florida community / events / local business
Posting allowed:
Yes, with limits
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes, minimized and community-relevant
Links allowed:
Yes when useful and locally relevant; avoid solicitation
Promo days or limits:
Keep posts local to Newberry, Florida. Minimize self-promotion, soliciting, and selling. Information must be useful and relevant to the community.
Best post style:
Useful local update / event / community resource
Allowed content buckets:
Marketplace / Creation Station / Farm updates / Community questions / Local business / Nonprofit community information
Do not post:
Do not use frequent self-promotion, direct donation asks, unrelated content, generic sales posts, or nonlocal information.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',218,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Happenings in Newberry County$g$,'Facebook','Group',$g$https://www.facebook.com/groups/yummyhomes/$g$,$g$Group type:
Public community group — Newberry, South Carolina
Posting allowed:
No
Donation posts allowed:
No
Business/program posts allowed:
No
Links allowed:
No
Promo days or limits:
Not applicable to the Florida service area; group rules also prohibit promotions and spam.
Best post style:
None
Allowed content buckets:
None
Do not post:
Do not use for Rebel Ranch Ministries Florida marketing.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',219,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Newberry: The Citizen’s Page$g$,'Facebook','Group',$g$https://www.facebook.com/groups/438655959864792/$g$,$g$Group type:
Public Newberry, Florida community / citizens
Posting allowed:
Yes, with limits
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes, once per week
Links allowed:
Yes only as part of the permitted once-weekly business post
Promo days or limits:
A business may self-promote once per week. Additional promotional posts are deleted. No duplicate posts, spammed comment ads, irrelevant links, anonymous posts, hate speech, or bullying.
Best post style:
Community-first post; limited local business promotion
Allowed content buckets:
Community questions / Marketplace / Farm updates / Local business
Do not post:
Do not post more than one business promotion per week, donation asks, duplicate posts, irrelevant links, anonymous content, or comment-flyer spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',220,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Citizens Of Newberry$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1717607998476802/$g$,$g$Group type:
Public Newberry, Florida community / citizens
Posting allowed:
No for Rebel Ranch marketing
Donation posts allowed:
No
Business/program posts allowed:
No self-promotion
Links allowed:
No for promotional use
Promo days or limits:
Businesses, employees, and family members may not promote or sell their own business or products. Repeated posts and spam are prohibited.
Best post style:
None for Rebel Ranch promotional content
Allowed content buckets:
None for marketing; independent community information only
Do not post:
Do not use for Rebel Ranch self-promotion, business/program advertising, product selling, donation asks, repeated posts, or promotional links.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',221,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$levy county Word Of Mouth!!! NO LIMITS!$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1063275977169664/$g$,$g$Group type:
Public Levy County community / word of mouth
Posting allowed:
No for Rebel Ranch marketing
Donation posts allowed:
No
Business/program posts allowed:
No self-promotion
Links allowed:
No promotional or irrelevant links
Promo days or limits:
Self-promotion, spam, and irrelevant links are prohibited. Business or organization bashing is prohibited; political and religious posts must be local.
Best post style:
None for Rebel Ranch promotional content
Allowed content buckets:
None for marketing
Do not post:
Do not rely on the group name as permission. Do not post self-promotion, donation asks, promotional links, spam, or business criticism.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',222,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Official - Levy County Florida Word of Mouth$g$,'Facebook','Group',$g$https://www.facebook.com/groups/763359049956167/$g$,$g$Group type:
Public Levy County community / word of mouth
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Local community question / useful business, program, or resource information
Allowed content buckets:
Community questions / Local resources / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not post unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',223,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Levy County Word of Mouth 2$g$,'Facebook','Group',$g$https://www.facebook.com/groups/218277925284562/$g$,$g$Group type:
Public Levy County community / word of mouth
Posting allowed:
Yes, with limits
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes, one ad per week
Links allowed:
No unless needed in the permitted weekly business ad
Promo days or limits:
No ordinary sales posts. Business ads are limited to one ad on one day per week; excess ads are deleted and may lead to a ban.
Best post style:
One useful local business ad or resource per week
Allowed content buckets:
Marketplace / Business Freedom / Local business
Do not post:
Do not post ordinary sales listings, more than one business ad per week, donation asks, duplicate promotions, or unrelated links.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',224,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Alachua County Word of Mouth$g$,'Facebook','Group',$g$https://www.facebook.com/groups/1788210135063398/$g$,$g$Group type:
Public Alachua County community / word of mouth
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Respectful community discussion / recommendation / useful local resource
Allowed content buckets:
Community questions / Local recommendations / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not post disrespectful content, unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',225,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Dixie county word of mouth$g$,'Facebook','Group',$g$https://www.facebook.com/groups/2835380093351994/$g$,$g$Group type:
Public Dixie County community / word of mouth
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Local community question / useful business, program, or resource information
Allowed content buckets:
Community questions / Local resources / Marketplace / Business Freedom / Creation Station / Farm updates / Support the Mission
Do not post:
Do not post unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',226,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Dixie, Levy, Gilchrist County Gossip$g$,'Facebook','Group',$g$https://www.facebook.com/groups/867571397545277/$g$,$g$Group type:
Public tri-county community discussion
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community question / rural community update / useful local resource
Allowed content buckets:
Community questions / Farm updates / Marketplace / Business Freedom / Creation Station / Support the Mission
Do not post:
Do not post personal allegations, harmful gossip, unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',227,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Gilchrist County Businesses$g$,'Facebook','Group',$g$https://www.facebook.com/groups/653263198981061/$g$,$g$Group type:
Public Gilchrist County business group
Posting allowed:
Yes
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes
Links allowed:
Yes, including business websites and Facebook links
Promo days or limits:
Family-friendly businesses only. Members may promote their own business, find local or online businesses, and give recommendations. Admins may not be blocked.
Best post style:
Direct local business resource / recommendation / business introduction
Allowed content buckets:
Business Freedom / Marketplace / Local business / Community questions
Do not post:
Do not post adult-business content, donation asks, disrespectful content, or anything that prevents admin oversight.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',228,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Gilchrist County Rants, Raves and Reviews$g$,'Facebook','Group',$g$https://www.facebook.com/groups/380577942652337/$g$,$g$Group type:
Public local reviews / discussion group
Posting allowed:
No for advertising
Donation posts allowed:
No
Business/program posts allowed:
No advertising or sales
Links allowed:
No promotional links
Promo days or limits:
The group is for rants, raves, and reviews, not advertisements or sales.
Best post style:
None for Rebel Ranch marketing
Allowed content buckets:
None for promotional content
Do not post:
Do not post advertisements, sales, program promotion, donation asks, promotional links, or shared promotional posts from other groups.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',229,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$),
($g$Citizens of Gilchrist County$g$,'Facebook','Group',$g$https://www.facebook.com/groups/437446924199845/$g$,$g$Group type:
Public Gilchrist County community / citizens
Posting allowed:
Yes, with limits
Donation posts allowed:
No for the current workflow unless separately confirmed
Business/program posts allowed:
Yes for a business listing or recommendation
Links allowed:
No unless separately confirmed
Promo days or limits:
Featured admin guidance invites members to list a business, online business, or business recommendation. No frequency or link rule was published.
Best post style:
Simple local business listing / recommendation / community resource
Allowed content buckets:
Marketplace / Business Freedom / Local business / Community questions
Do not post:
Do not post donation asks, repeated ads, or external links until those uses are explicitly confirmed.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',230,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Citizens of Gilchrist County Fl.$g$,'Facebook','Group',$g$https://www.facebook.com/groups/266638974913836/$g$,$g$Group type:
Public Gilchrist County community / citizens
Posting allowed:
Yes, under the owner-approved no-published-restriction rule
Donation posts allowed:
Yes, when directly relevant and used sparingly
Business/program posts allowed:
Yes, when locally relevant
Links allowed:
Yes, when directly relevant to the post
Promo days or limits:
No published schedule or frequency limit. Use one locally relevant post at a time, avoid duplicate blasting, and check posted-archive.md before reuse.
Best post style:
Community update / useful local business, program, or resource information
Allowed content buckets:
Community questions / Farm updates / Marketplace / Business Freedom / Creation Station / Support the Mission
Do not post:
Do not post sensitive incident identities, unrelated promotions, duplicate content, deceptive links, or spam.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Active',231,$g$Imported from group-rules.md (audited 2026-08-16): Approved.$g$),
($g$Florida Camping and Outdoors$g$,'Facebook','Group',$g$https://www.facebook.com/groups/285452389066838/$g$,$g$Group type:
Public Florida camping / outdoor-interest group
Posting allowed:
No for Rebel Ranch marketing
Donation posts allowed:
No
Business/program posts allowed:
No promotions or sales
Links allowed:
No promotional links
Promo days or limits:
Content must concern camping and outdoor activity, preferably Florida. Promotions, spam, sales, purchases, and merchandise are prohibited; content must remain clean and family-friendly.
Best post style:
None for routine Rebel Ranch marketing
Allowed content buckets:
None for promotional content
Do not post:
Do not post Business Freedom, Marketplace, donation asks, product sales, program promotion, or unrelated farm content.
(Full audit notes: marketing/social-media/group-rules.md)$g$,'Archived',232,$g$Imported from group-rules.md (audited 2026-08-16): Do not use. Kept for the record; do not post here.$g$)
on conflict (name) do nothing;

insert into public.social_links (label, url, program_id, purpose_id, notes)
select v.label, v.url, p.id, pu.id, v.notes
from (values
  ('Rebel Ranch Ministries — Home','https://rebelranchministries.org/','Rebel Ranch Ministries',null,null),
  ('Support the Mission (donate)','https://rebelranchministries.org/support.html','Rebel Ranch Ministries','Donations',null),
  ('Programs Hub','https://rebelranchministries.org/programs.html','Rebel Ranch Ministries',null,null),
  ('Marketplace','https://rebelranchministries.org/marketplace.html','Rebel Ranch Local / Marketplace',null,null),
  ('Business Freedom','https://rebelranchministries.org/business-fixes.html','Business Freedom',null,null),
  ('Creation Station','https://rebelranchministries.org/creation.html','Creation Station',null,null),
  ('Rebel Ranch Academy','https://academy.rebelranchministries.org/','Rebel Ranch Academy',null,null),
  ('FFN Church','https://ffnchurch.org/','Faith, Family, and Nature Church',null,null)
) as v(label,url,program,purpose,notes)
left join public.social_programs p on p.name = v.program
left join public.social_purposes pu on pu.name = v.purpose
where not exists (select 1 from public.social_links l where l.url = v.url);

insert into public.social_campaigns (name, program_id, purpose_id, link_id, goal, start_date, status, notes)
select v.name, p.id, pu.id, l.id, v.goal, v.start_date::date, v.status, v.notes
from (values
  ('2026-08 Launch','Rebel Ranch Local / Marketplace','Program Promotion','https://rebelranchministries.org/marketplace.html','Two-week Rebel Ranch Local launch sequence (RRL-01 to RRL-14).','2026-08-22','Active',null),
  ('2026-08-16 Facebook Batch','Rebel Ranch Ministries',null,null,'First approved 2-week batch across programs (imported from draft-posts.md).','2026-08-16','Active',null),
  ('GoFundMe Fundraiser','Rebel Ranch Ministries','Fundraiser (GoFundMe)',null,'Drive support to the Rebel Ranch Ministries GoFundMe.',null,'Planned','Add the GoFundMe link in Setup → Links, then pick it as this campaign''s link.'),
  ('Local Partner Outreach 2026','Rebel Ranch Ministries','Partnerships & Sponsors',null,'Chambers, local businesses, service clubs and agencies across Gilchrist, Alachua, Levy and Dixie counties.','2026-08-16','Active','Imported from marketing/partner-outreach/outreach-queue.md.')
) as v(name,program,purpose,link,goal,start_date,status,notes)
left join public.social_programs p on p.name = v.program
left join public.social_purposes pu on pu.name = v.purpose
left join public.social_links l on l.url = v.link
on conflict (name) do nothing;

-- Backfill the 14 existing Rebel Ranch Local launch items.
update public.social_content_items i set
  program_id = (select id from public.social_programs where code = 'RRL'),
  campaign_id = (select id from public.social_campaigns where name = '2026-08 Launch'),
  link_id = (select id from public.social_links where url = 'https://rebelranchministries.org/marketplace.html'),
  channel_ids = array(select id from public.social_channels where name in ('Rebel Ranch Facebook Page','Rebel Ranch Instagram') order by sort_order),
  purpose_id = (select id from public.social_purposes where name = case
      when i.goal ilike '%seller%' or i.goal ilike '%registration%' then 'Seller & Provider Recruitment'
      when i.goal ilike '%comment%' then 'Community Input'
      when i.goal ilike '%trust%' or i.goal ilike '%awareness%' or i.goal ilike '%mission%' then 'Brand Awareness'
      when i.goal ilike '%education%' or i.goal ilike '%usage%' then 'Education'
      else 'Program Promotion' end),
  image_status = case
      when exists (select 1 from public.social_content_assets a where a.content_item_id = i.id and a.asset_status = 'Approved') then 'Approved'
      when exists (select 1 from public.social_content_assets a where a.content_item_id = i.id) then 'Needs Review'
      else 'Prompt Needed' end,
  source_ref = coalesce(i.source_ref, 'social_content_hub_v1 seed')
where i.program = 'Rebel Ranch Local' and i.program_id is null;

-- Import the 8 approved drafts from marketing/social-media/draft-posts.md (batch 2026-08-16).
with src(n, program_code, purpose, title, audience, format, image_needed, image_status, image_prompt, link, channels, cta, caption, notes) as (values
(1,'BF','Program Promotion','Business Freedom — Real help. Real fixes.','Small business owners','Standalone',true,'Approved',null,'https://rebelranchministries.org/business-fixes.html',array['Rebel Ranch Facebook Page'],'Explore Business Freedom',
$t$Small business owners do not need more noise.

They need real help, real visibility, and a fair shot.

Business Freedom was built for sole operators and working people who are tired of duct-taping everything together — missed leads, messy systems, money leaks, payment issues, websites, social media, and all the little things that steal time every single week.

This is practical business help through Rebel Ranch Ministries.

Real help. Real fixes. Real community.

Explore Business Freedom:
https://rebelranchministries.org/business-fixes.html$t$,
$t$Goal: introduce Business Freedom as available now without sounding corporate. Page post only for now. Use Rebel Ranch branded graphic; no 3P logo unless specifically approved. Canva: https://www.canva.com/d/m9Jg-Gc7qGn282_/$t$),
(2,'RRM','Donations','Support the Mission — the part people don''t see','Everyone','Standalone',true,'Approved',null,'https://rebelranchministries.org/support.html',array['Rebel Ranch Facebook Page','Brooke — Personal Facebook'],'Support the mission',
$t$This is the part people do not always see.

The animals, the fencing, the supplies, the feed, the tools, the cleanup, the program materials — it all costs money before a program ever gets built.

Rebel Ranch Ministries is building real boots-on-the-ground programs for families, kids, local businesses, and our community.

Every donation helps move the work forward.

Support the mission.
Help fund the boots-on-the-ground work.

https://rebelranchministries.org/support.html

Donations may be tax-deductible as allowed by law.

Faith. Family. Nature.
Faith, Family & Freedom.$t$,
$t$Goal: ask for support without guilt marketing. Do not use in Facebook groups unless donation posts are allowed. Tax wording included. Graphic must show the whole people-building ecosystem, not only pigs/fencing/feed. Canva: https://www.canva.com/d/H_qw8rG9QpUuzFV$t$),
(3,'RRL','Program Promotion','Marketplace — Local people need a platform too','Buyers and local businesses','Standalone',true,'Approved',null,'https://rebelranchministries.org/marketplace.html',array['Rebel Ranch Facebook Page'],'Tag a local business that should be seen',
$t$Big Business has enough platforms.

Local people need one too.

Rebel Ranch Marketplace is being built for small businesses, food trucks, makers, growers, families, and sole operators who need a level playing-field.

Buy local.
Shop local.
Build local.

This is not just a directory. It is a local support system with business resources available from a real professional business consultant.

Visit the Marketplace:
https://rebelranchministries.org/marketplace.html

Tag a local business that should be seen.$t$,
$t$Goal: promote Marketplace and encourage engagement. Can be adapted for local business groups if promo posts are allowed. Must say level playing-field, not approved-only directory. Canva: https://www.canva.com/d/qOhABqcOmTvvUQI$t$),
(4,'BF','Community Input','Real question for small business owners','Small business owners','Text Only',false,'Not Needed',null,null,array['Rebel Ranch Facebook Page'],'Drop the real answer',
$t$Small business owners — real question.

What is the one thing you wish more people understood about running your own business?

The long hours?
The missed family time?
The money pressure?
The fact that everything falls back on you?

Drop the real answer.

No polished business talk. Just the truth.$t$,
$t$Goal: start conversation with local small business owners. Good for groups if business discussion is allowed. No link needed. Could use a simple Rebel Ranch question graphic.$t$),
(5,'RRM','Behind the Scenes','Farm update — building before it looks pretty','Everyone','Standalone',true,'Needs Review',null,'https://rebelranchministries.org/support.html',array['Rebel Ranch Facebook Page','Brooke — Personal Facebook'],'Support the mission',
$t$This is what building looks like before it looks pretty.

Fencing, animals, feed, cleanup, repairs, supplies, and a whole lot of work that does not fit into a perfect little post.

But this is the work.

Rebel Ranch Ministries is building programs around real-life skills, sustainability, animals, food, family, and community.

The boots-on-the-ground work matters.

Support the mission:
https://rebelranchministries.org/support.html$t$,
$t$Goal: use real farm updates to show progress and need. Avoid donation link in groups unless allowed. Five image options are attached — pick one (approve it) or use a real photo: pigs, fence, supplies, animals, garden, boots, work-in-progress.$t$),
(6,'CS','Program Promotion','Creation Station — more than another screen','Families and young creators','Standalone',true,'Ready for Image',
$t$Realistic photo-style image of kids around 7–12 and a parent at a kitchen or workshop table doing a hands-on creative project with simple materials (paper, paint, cardboard, yarn, markers). Warm natural light, real mess, real concentration and pride. Kid-friendly but not childish, not corporate, no screens. Leave clean space at the top for the headline "More than another screen." Creation Station sub-brand: cream background tones with purple and soft rainbow accents. Square 1080×1080.$t$,
'https://rebelranchministries.org/creation.html',array['Rebel Ranch Facebook Page'],'Learn more',
$t$Creation Station is for young creators who need more than another screen.

Hands-on projects.
Real creativity.
Simple materials.
Families building confidence through making something real.

These are creative sessions, not boring classes.

Rebel Ranch Ministries is building programs that give kids and families something real to do, build, try, and learn.

Learn more:
https://rebelranchministries.org/creation.html$t$,
$t$Goal: promote Creation Station as available. Can be adapted for homeschool/family groups if allowed. Image still needed (prompt ready for ChatGPT).$t$),
(7,'RRA','Program Promotion','Rebel Ranch Academy — real-life skills','Families','Standalone',true,'Approved',null,'https://academy.rebelranchministries.org/',array['Rebel Ranch Facebook Page'],'Follow along',
$t$Rebel Ranch Academy is being built around something simple:

Kids and families need real-life skills.

Not fake worksheets about life.
Actual life.

Growing food.
Working with animals.
Working with people.
Learning sustainability.
Using your hands.
Understanding where food comes from.
Building confidence through real work.

Roots, Boots & Animal Poops is part of that world — because learning does not have to be polished to matter.

Rebel Ranch Academy is still being built, but this is where we are headed.$t$,
$t$Goal: talk about the Academy without claiming enrollment or full availability. Page post; be careful in groups. General Academy overview — agriculture/animals may appear but must not dominate. Draft had no link; Academy link added — remove if not wanted. Canva: https://www.canva.com/d/acefj-ewGStW22w$t$),
(8,'RRL','Community Input','Local question — do you buy local first?','Everyone','Text Only',false,'Not Needed',null,null,array['Rebel Ranch Facebook Page'],'Tell us what would make it easier',
$t$Local question:

When you choose where to spend money, do you try to buy local first?

Food trucks, farms, small shops, services, makers, growers — all of it.

Big Business gets seen automatically.

Local people have to fight for every bit of visibility.

What would make it easier for you to find and support local businesses?$t$,
$t$Goal: start conversation around the Marketplace need. Good for local groups if discussion posts are allowed. No image required.$t$)
),
ins as (
  insert into public.social_content_items
    (program_id, purpose_id, campaign_id, title, audience, goal, caption, cta, format, status,
     image_needed, image_status, image_prompt, link_url, channel_ids, notes, source_ref, campaign_day)
  select p.id, pu.id, c.id, s.title, s.audience, s.purpose, s.caption, s.cta, s.format, 'Approved',
         s.image_needed, s.image_status, s.image_prompt, s.link,
         array(select ch.id from public.social_channels ch where ch.name = any(s.channels) order by ch.sort_order),
         s.notes, 'draft-posts.md #' || s.n, s.n
  from src s
  join public.social_programs p on p.code = s.program_code
  join public.social_purposes pu on pu.name = s.purpose
  cross join (select id from public.social_campaigns where name = '2026-08-16 Facebook Batch') c
  where not exists (select 1 from public.social_content_items x where x.source_ref = 'draft-posts.md #' || s.n)
  returning id, source_ref
)
insert into public.social_content_assets (content_item_id, asset_kind, asset_status, master_filename, preview_path, notes)
select ins.id, 'image', v.status, v.file, 'marketing/social-media/visuals/2026-08-16-facebook-batch/' || v.file, v.notes
from ins
join (values
  ('draft-posts.md #1','draft-01-business-freedom.png','Approved',null),
  ('draft-posts.md #2','draft-02-support-the-mission.png','Approved',null),
  ('draft-posts.md #3','draft-03-rebel-ranch-marketplace.png','Approved',null),
  ('draft-posts.md #7','draft-07-rebel-ranch-academy.png','Approved',null),
  ('draft-posts.md #5','farm-update-review-variants/draft-05-soil-regeneration-v1.png','Needs Review','Option 1 of 5'),
  ('draft-posts.md #5','farm-update-review-variants/draft-05-homesteading-basics.png','Needs Review','Option 2 of 5'),
  ('draft-posts.md #5','farm-update-review-variants/draft-05-regeneration-cycle-v1.png','Needs Review','Option 3 of 5'),
  ('draft-posts.md #5','farm-update-review-variants/draft-05-soil-regeneration-rabbits-worms.png','Needs Review','Option 4 of 5'),
  ('draft-posts.md #5','farm-update-review-variants/draft-05-regeneration-cycle-rabbits-worms.png','Needs Review','Option 5 of 5')
) as v(src, file, status, notes) on v.src = ins.source_ref;

-- Import the 13 entries from marketing/partner-outreach/outreach-queue.md. Nothing has been sent.
insert into public.social_outreach
  (ref, target_name, category, target_type, program_id, purpose_id, campaign_id, contact_method,
   contact_name, contact_email, contact_phone, website, contact_details, offer_ask, subject, message,
   status, time_sensitivity, research_needed, notes, source_ref, created_at)
select v.ref, v.target, v.category, v.target_type, p.id, pu.id, c.id, v.method,
       v.contact_name, v.email, v.phone, v.website, v.details, v.ask, v.subject, v.message,
       v.status, v.time_sens, v.research, v.notes, 'outreach-queue.md Entry ' || v.entry, v.created::timestamptz
from (values
('OUT-001',1,'Gilchrist County Chamber of Commerce','General alignment','Chamber of commerce','RRM','Partnerships & Sponsors','Facebook message',null,null,'352-463-3467','https://www.facebook.com/GilchristChamber',
 $t$Phone (352-463-3467) or in person, 112 S Main St, Trenton, FL. Hours limited (Mon/Tue 9-2, Wed/Thu 10-3, closed Fri-Sun). No public email found — Facebook page message or phone call.$t$,
 $t$Introduce Rebel Ranch Ministries as a local resource hub (Business Freedom, Marketplace, Creation Station, Academy) and ask what the Chamber needs to list/feature a local organization to its member businesses.$t$,
 null,
 $t$Hi — I'm reaching out from Rebel Ranch Ministries, based right here in Gilchrist County. We're building a few things local folks might find useful: free practical help for small business owners who are stretched thin (Business Freedom), a local marketplace for makers, growers, and small businesses to get seen, and hands-on learning programs for kids and families.

We'd love to get on the Chamber's radar and hear what it takes to be listed or featured for your member businesses. Happy to talk by phone or by message — whatever's easiest for you.

I saw membership is discounted for nonprofits — could you let me know what that costs, and roughly how many people see the member directory, newsletter, or Facebook page? Just trying to understand what membership would actually get us before committing.

Thanks for everything you do for Gilchrist County businesses.$t$,
 'Draft','None known.',$t$Confirm best contact channel (no public email). Draft works as a Facebook message or a phone-call talking point.$t$,
 $t$Highest-value local relationship — one Chamber contact can open visibility to many Gilchrist County businesses at once.$t$,'2026-08-16'),
('OUT-002',2,'Newberry Area Chamber of Commerce','General alignment','Chamber of commerce','RRM','Partnerships & Sponsors','Web form',null,null,null,'https://newberryareachamber.com/contact/',
 $t$Contact form at newberryareachamber.com/contact/ or Facebook page (facebook.com/NewberryAreaChamberFL).$t$,
 $t$Ask about (a) listing Rebel Ranch events/programs on their public calendar and (b) what membership/listing looks like for a local nonprofit ministry.$t$,
 null,
 $t$Hi — my name is Brooke, and I run Rebel Ranch Ministries, working out of the Newberry/Gilchrist area. We're building practical programs for local families and small businesses — hands-on learning for kids (Creation Station), real help for small business owners who are drowning in the day-to-day (Business Freedom), and a local marketplace for makers and growers.

A couple of questions: what does it take to get an event or program listed on your community calendar, and for the $75/year nonprofit membership — roughly how many people actually see the directory, newsletter, or calendar? Just want to understand what it'd actually get us before joining.

Would love to be part of what's happening in Newberry.$t$,
 'Draft','None known.',$t$Confirm what Chamber membership includes before committing beyond the first ask.$t$,
 $t$Ongoing, low-effort visibility channel (public event calendar) plus explore membership.$t$,'2026-08-16'),
('OUT-003',3,'Newberry Watermelon Festival (2026 — May 16)','Other','Event organizer','RRM','Partnerships & Sponsors','Email',null,'nwfvendor@gmail.com',null,null,null,
 $t$Vendor/craft booth space and parade entry.$t$,
 null,
 $t$Hi — I'm reaching out about the 2026 Newberry Watermelon Festival. My organization, Rebel Ranch Ministries, is based locally and runs a few community programs — a local marketplace for small businesses and makers, hands-on learning for kids, and family/business support work.

We'd love to have a presence at the festival — either a booth/table or an entry in the parade — and wanted to ask about availability, cost, and what the application process looks like for a local community organization.

Thanks, and looking forward to a great festival this year.$t$,
 'Rejected',null,null,
 $t$Brooke rejected the vendor/booth model outright on 2026-08-16 ("im not going to a festival as a vendor"). Kept for the record. Do not revive this framing.$t$,'2026-08-16'),
('OUT-004',4,'High Springs Chamber of Commerce','General alignment','Chamber of commerce','RRM','Partnerships & Sponsors','Email',null,'Chamber@highsprings.com',null,null,null,
 $t$Introduce Rebel Ranch Ministries and ask about vendor terms for the Pioneer Day Festival (April 25-26, 2026) and the Fall Festival.$t$,
 'Local ministry interested in your festival vendor opportunities',
 $t$Hi,

My name is Brooke, and I run Rebel Ranch Ministries — we're a local ministry building practical programs for families: hands-on learning for kids, real support for small business owners, and a marketplace for local makers and growers.

I saw High Springs hosts both a Pioneer Day Festival and a Fall Festival that welcomes vendors. I'd love to learn more about what it takes to have a presence at either one — cost, application process, and what kind of booth/table setup is expected.

Thanks for your time, and looking forward to hearing from you.

Brooke
Rebel Ranch Ministries$t$,
 'Draft','Moderate — Pioneer Day is April 25-26, 2026.',$t$Exact vendor cost/deadline — the message asks directly.$t$,
 $t$FLAG: this draft uses vendor/booth framing, which Brooke rejected for festivals on 2026-08-16 (see OUT-003). Rewrite as a community introduction or mark Rejected before sending. Physical presence would also be required.$t$,'2026-08-16'),
('OUT-005',5,'Dixie County Chamber of Commerce','General alignment','Chamber of commerce','RRM','Partnerships & Sponsors','Email',null,'info@dixiechamber.org',null,null,null,
 $t$Introduce Rebel Ranch Ministries as a regional resource and ask how the Chamber connects local organizations with member businesses.$t$,
 'Introduction — Rebel Ranch Ministries',
 $t$Hi,

My name is Brooke, and I run Rebel Ranch Ministries. We're based in Gilchrist County and work across the surrounding area — practical support for small business owners, a local marketplace for makers and growers, and hands-on learning programs for kids and families.

I wanted to introduce Rebel Ranch to the Dixie County Chamber and ask how you connect local organizations with your member businesses and community — whether that's a newsletter mention, an event listing, or something else.

Thank you for the work you do for Dixie County.

Brooke
Rebel Ranch Ministries$t$,
 'Draft','None known.',null,
 $t$Low-effort first contact into Dixie County — real email address, no travel or call needed.$t$,'2026-08-16'),
('OUT-006',6,'Suwannee Valley Feeds','B — Service/resource exchange','Local business','RBAP','Partnerships & Sponsors',null,null,null,null,null,
 $t$Needs direct lookup — serves Gilchrist County plus Bell, Branford, Fanning Springs and Chiefland; no confirmed phone or email yet.$t$,
 $t$Cross-promotion: mention each other to shared customers, or refer families to them for supplies.$t$,
 null,
 $t$Hi — I'm Brooke with Rebel Ranch Ministries, right here in Gilchrist County. We're building a hands-on agriculture and animal care program (part of Rebel Ranch Academy) and work with families raising and caring for animals across the same area you serve.

I'd love to talk about ways we could support each other — whether that's mentioning Suwannee Valley Feeds to our families as a trusted local supplier, or something else that makes sense for you.

Would love to connect when you have a few minutes.$t$,
 'Needs Edit','None known.',$t$Confirmed phone number or email before this can move forward.$t$,
 $t$Check program naming: the charter lists Roots, Boots & Animal Poops as its own RRM program — the draft calls it "part of Rebel Ranch Academy".$t$,'2026-08-16'),
('OUT-007',7,'Rotary Club of Gilchrist County','A — Fund request','Community organization','RRM','Donations','Facebook message',null,null,null,'https://gilchristrotary.org',
 $t$Facebook page (facebook.com/GilchristRotary.org) or gilchristrotary.org. Club meets Mondays 12-1pm at the Gilchrist Women's Club in Trenton.$t$,
 $t$Ask to present Rebel Ranch Ministries as a guest speaker (the usual first step before funding) and what local causes the club supports.$t$,
 null,
 $t$Hi — my name is Brooke, and I run Rebel Ranch Ministries here in Gilchrist County. We run a few practical local programs: hands-on learning for kids, real help for small business owners, and a marketplace for local makers and growers.

I'd love the chance to come speak to the club sometime about what we're building and how it fits with what Rotary already supports locally. Is that something I could get on a future meeting's schedule for?

Thank you for everything the club does for Gilchrist County.$t$,
 'Draft','None known — club meets weekly.',null,
 $t$Relationship first, not a cold donation ask. Speaking in person requires transportation — confirm before sending.$t$,'2026-08-16'),
('OUT-008',8,'Tractor Supply — Newberry location','B — Service/resource exchange','Local business','RBAP','Partnerships & Sponsors','Phone',null,null,null,null,
 $t$Newberry store, 14151 W Newberry Rd, Newberry, FL 32669. Store managers handle community donation requests directly. No store email found — phone or a written note.$t$,
 $t$In-kind donation of supplies (feed, fencing, basic equipment) in exchange for featuring Tractor Supply as a supporting local partner.$t$,
 null,
 $t$Hi — I'm Brooke with Rebel Ranch Ministries, a local ministry running a hands-on animal care and agriculture program (part of Rebel Ranch Academy) here in Gilchrist County.

I know Tractor Supply supports local community requests directly through individual stores. We could really use some help with supplies — feed, fencing materials, or basic equipment — for the animals and programs we're building. In return, we'd be glad to feature Tractor Supply as a supporting local partner in our program materials and social media.

As a church, any donation is tax-deductible, and we're glad to provide a donation letter for your records.

Would love to talk about what might make sense.$t$,
 'Draft','None known.',$t$Confirm the best way to reach the store directly (phone vs. in person).$t$,null,'2026-08-16'),
('OUT-009',9,'Seacoast Bank — Chiefland Branch','A — Fund request','Local business (bank)','RRM','Donations','Phone',null,null,'(352) 493-2277',null,
 $t$By appointment — 1627 N Young Blvd, Chiefland.$t$,
 $t$Ask about Seacoast Bank's Community Giving Program and whether Rebel Ranch Ministries is a fit for a contribution or sponsorship.$t$,
 null,
 $t$Hi — my name is Brooke, and I run Rebel Ranch Ministries, based in Gilchrist County. I saw Seacoast Bank has a Community Giving Program and wanted to introduce our work — practical programs for local families, including hands-on learning for kids, help for small business owners, and a marketplace for local makers and growers.

Could I set up a time to talk about whether Rebel Ranch might be a fit for the Community Giving Program? As a church, any contribution is tax-deductible, and we're glad to provide a donation letter for your records.

Thank you for supporting Chiefland and the surrounding community.$t$,
 'Draft','None known.',null,null,'2026-08-16'),
('OUT-010',10,'UF/IFAS Extension Gilchrist County — 4-H program','Program affiliation','Government/extension office','RBAP','Partnerships & Sponsors','Email','Jessica Altum-Cooper (Director)','gilchrist@ifas.ufl.edu','(352) 463-3174',null,
 $t$Director Jessica Altum-Cooper (jaltum@ufl.edu). Office in Trenton.$t$,
 $t$Ask what it takes to start a 4-H club through the animal program — kids/families/leader requirements, background screening and training.$t$,
 null,
 $t$Hi — my name is Brooke, and I run Rebel Ranch Ministries in Trenton. We have a hands-on Animal Husbandry program (part of Rebel Ranch Academy) where kids work with animals, learn agriculture and sustainability, and build real-life skills.

I'd like to look into starting a 4-H club through our program. Could you walk me through what's needed — the volunteer background screening process, how many kids/families we'd need, and what getting started actually looks like?

Thank you for everything the Extension office does for Gilchrist County.$t$,
 'Draft','None known.',null,
 $t$A program decision as much as a funding one (background-screened volunteer leaders, ongoing structure). Opens the youth funding lane that Walmart/Tractor Supply sponsorships flow through.$t$,'2026-08-17'),
('OUT-011',11,'Chiefland Ford / Big Bend Chevrolet Buick','B — Service/resource exchange','Local business (car dealership)','RRM','Partnerships & Sponsors',null,null,null,null,null,
 $t$916 N Young Blvd and 1424 N Young Blvd, Chiefland. No confirmed direct email — likely phone or sales desk.$t$,
 $t$Vehicle donation, trade-in credit toward an organizational vehicle, or sponsorship — featured as a supporting local partner in return.$t$,
 null,
 $t$Hi — my name is Brooke, and I run Rebel Ranch Ministries, a local church and ministry in Trenton with hands-on programs for kids and families — Animal Husbandry, business support, and youth learning.

We're looking into options for a dependable vehicle for program use — hauling supplies, transporting animals and materials, getting to local events. I wanted to ask whether you'd consider a vehicle donation, a trade-in credit toward something on your lot, or a sponsorship arrangement. As a church, any donation is tax-deductible, and we're glad to provide a donation letter for your records. In return, we'd be glad to feature you as a supporting local partner in our materials and social media.

Happy to talk through what might make sense.$t$,
 'Needs Edit','None known.',$t$Confirmed direct contact method.$t$,null,'2026-08-17'),
('OUT-012',12,'Love Power Equipment & Rentals (ATV/UTV dealer, Chiefland)','B — Service/resource exchange','Local business (powersports dealer)','RBAP','Partnerships & Sponsors','Phone',null,null,'(352) 493-1770',null,null,
 $t$Donated or discounted side-by-side/UTV for ranch work, featured as a supporting partner in return.$t$,
 null,
 $t$Hi — my name is Brooke with Rebel Ranch Ministries in Trenton. We run a hands-on Animal Husbandry program where kids and families work with animals and learn real agriculture and ranch skills.

We could really use a side-by-side or UTV for day-to-day ranch work — hauling feed, checking fence lines, getting around the property. I wanted to ask whether you'd consider a donation or a discounted unit. As a church, any donation is tax-deductible, and we're glad to provide a donation letter for your records. Happy to feature Love Power Equipment as a supporting local partner in return.

Would love to talk when you have a few minutes.$t$,
 'Draft','None known.',null,null,'2026-08-17'),
('OUT-013',13,'Blue Gill (Newberry restaurant)','B — Service/resource exchange','Local business (restaurant)','RRM','Partnerships & Sponsors',null,null,null,null,null,
 $t$Needs direct lookup — no confirmed phone/email yet.$t$,
 $t$Food/catering donation for volunteer appreciation or events, in exchange for cross-promotion.$t$,
 null,
 $t$Hi — my name is Brooke with Rebel Ranch Ministries, a local church and ministry here in the Newberry/Gilchrist area. We run hands-on programs for kids and families and could use some help feeding the volunteers who make it happen.

Would Blue Gill ever be open to donating food or a catering credit for one of our events or volunteer days? As a church, any donation is tax-deductible, and we're glad to provide a donation letter for your records. We'd love to promote Blue Gill to our community in return — real local food deserves to be seen.

Thanks for everything you bring to Newberry.$t$,
 'Needs Edit','None known.',$t$Confirmed contact method.$t$,null,'2026-08-17')
) as v(ref, entry, target, category, target_type, program_code, purpose, method, contact_name, email, phone, website, details, ask, subject, message, status, time_sens, research, notes, created)
left join public.social_programs p on p.code = v.program_code
left join public.social_purposes pu on pu.name = v.purpose
cross join (select id from public.social_campaigns where name = 'Local Partner Outreach 2026') c
on conflict (ref) do nothing;

insert into public.social_activity_log (entity_type, entity_id, action, detail, actor, user_id)
values ('system', null, 'Hub v2 installed',
        'All-programs control panel: managed programs/purposes/campaigns/links/channels, scheduling, image workflow, uploads, outreach (13 imported), 8 drafts imported, learning loop.',
        'Claude', null);
